src/examples/serial/serial.go

Adds "Hello, world" serial port communication example that was unintentionally committed to AVR ADC branch.

Add hello world serial communication example

---

compiler/compiler.go
src/runtime/string.go
testdata/binop.go
testdata/binop.txt

add stringCmp(). Not fully tested if I haven't made an error.
Improve the test a bit to be more readable.

compiler: implement binop string: <, <=, >, >=

---

src/examples/wasm/wasm.go
src/examples/wasm/wasm.html
src/examples/wasm/wasm.js
targets/wasm_exec.js

WIP: syscall/js support

---

src/runtime/runtime_atsamd21g18.go

This PR corrects the clock calibration for the SAMD21's 48MHz clock by using the stored fuse calibration value for the DFLL clock source.

machine/atsamd21: correct clock calibration based on stored fuse value

---

src/machine/board_itsybitsy-m0.go
src/machine/machine_atsamd21g18.go
src/runtime/runtime_atsamd21g18.go

This PR implements the PWM interface for the SAMD21 family of processors.

Implement PWM interface for SAMD21

---

CONTRIBUTING.md

Added contribution docs to help people understand how to use the git branches, etc.

Add CONTRIBUTING.md to help us help you

---

.travis.yml
targets/nrf52.json
targets/nrf52840.json

This lets us test with a more recent base, and should fix various issues.

all: update Travis CI to Ubuntu Xenial

---

src/machine/machine_atsamd21.go

I think this is not complete yet. Also, not yet tested very well.

samd21: add GPIO support for port B

---

.travis.yml
main_test.go
target.go

This avoids an error on the Raspberry Pi 3.

arm: switch to hardfloat ABI for Linux

---

.circleci/config.yml
main_test.go
targets/wasm.json
targets/wasm_exec.js

Depends on #130. There are only 3 commits left after that PR gets merged.

Add tests for WebAssembly

---

targets/wasm_exec.js

The wasm_exec.js file copied from the main Go repository did write those values to address 4096 in linear memory, which led to memory corruption in linear memory. Remove these things for now, until they're actually supported, if support is ever added.
I'm surprised we didn't hit this issue in CI, but I did hit it locally.

wasm: ignore arguments and environment variables

---

interp/interp.go

Whenever interp hits an unreachable instruction, it bails out at that point. However, it used to insert new instructions at the bottom with the old init calls still at the top. So when a `panic()` happened in a non-main package, the last packages to init would actually be called first.
This commit fixes this by setting the insert point at the top of `runtime.initAll` before starting interpretation, so the initialization order is still correct when a `panic()` happens during init.
Found while working on Go 1.12 support.

interp: use correct initialization order on panic() calls

---

compiler/compiler.go

This PR performs a few optimizations that mostly affect memory operations (slices etc.).
This improves some programs. For example, examples/blinkm when compiled for the micro:bit shrank from 8536 bytes to 8424.

Optimize slices

---

.circleci/config.yml
Makefile
loader/libclang.go
src/reflect/type.go
src/reflect/value.go
src/runtime/internal/sys/zversion.go

Make sure all files are formatted before checking them in. Also, fix formatting of a few files I accidentally let slip through.
I've put the check at the end of the build so CircleCI won't stop the test just because the formatting isn't right.

all: check formatting on CI

---

Makefile

This PR removes various Makefile tasks that are redundant thanks to TinyGo improvements.

tools: remove Makefile tasks that are now redundant

---

compiler/compiler.go
compiler/interface.go
compiler/sizes.go
loader/libclang.go
loader/sync.go
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

I think this covers the majority of C types.

cgo: implement structs, arrays, and unions

---

compiler/compiler.go
loader/cgo.go
loader/libclang.go
loader/libclang_stubs.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

This looks like the underlying issue that I was battling with in #266.

cgo: fix stack overflow in linked list

---

loader/cgo.go
loader/libclang.go
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

Implement some features required for CGo on macOS. This is in preparation of #266.

cgo: implement some features required for macOS

---

src/examples/wasm/README.md
src/examples/wasm/server.go

Adjusted as per @aykevl request in https://github.com/tinygo-org/tinygo-site/pull/22#issuecomment-489193706.

example: just using 'Cache-Control': 'no-cache' should be good enough

---

.gitignore

Add llvm directorys to gitignore

---

src/machine/machine_nrf.go

Fix for https://github.com/tinygo-org/tinygo/issues/343

Fix I2C signalStop in readLastByte for Microbit

---

src/machine/machine_nrf.go

Revert "Fix I2C signalStop in readLastByte for Microbit"

---

cgo/cgo.go
ir/ir.go
loader/loader.go

Just stuff noticed while looking through the code.  All completely trivial. :wink:

Trivial typo fixes

---

compiler/channel.go
compiler/compiler.go
compiler/llvm.go
compiler/map.go
compiler/wordpack.go

Make sure all allocas are created in the entry block and are given the
right lifetimes. This is good for code quality:
* Moving allocas to the entry block makes sure they are always
allocated statically (avoiding the need for a frame pointer) and do
not grow the stack on each new alloca instruction. This is
especially useful in loops where it could otherwise lead to a stack
overflow even though there is no recursion.
* Adding lifetime markers allows LLVM to reuse stack areas for
different allocas as long as their lifetimes do not overlap.
All in all, this reduces code size in all tested cases for the BBC
micro:bit, and reduces code size for most cases for WebAssembly.

compiler: create temporary allocas with appropriate lifetimes

---

interp/frame.go

I've found the issue, this should fix it.
See #363

Fix "branch was not true or false" in some cases

---

src/machine/machine_atsamd21e18.go
src/machine/machine_atsamd21g18.go

Not verified myself, but it clearly looks like a copy-paste bug.

machine/atsamd21: fix analog pin mode

---

.circleci/config.yml
Makefile

1. Move smoke tests into the Makefile
2. Add a smoketest for each example.

Improve tests

---

interp/frame.go
interp/utils.go

interp: support some more expressions in const icmp

---

Makefile
src/machine/machine_nrf.go
src/machine/machine_nrf51.go
src/machine/machine_nrf52.go
src/machine/machine_nrf52840.go
src/runtime/runtime_nrf.go

This PR refactors the NRF boards to use the volatile package/API. It needs to have at least issue #363 addressed before it can be merged.

machine/nrf: refactor to use volatile package/API

---

compiler/compiler.go
compiler/func.go
compiler/map.go
compiler/syscall.go

Two commits that are necessary for #285, and two other smaller changes that I found while working on #285.

Some compatibility fixes

---

Makefile

`LLVM_BUILDDIR` can be overridden by environment variable, so might as well adjust the rest of the Makefile to use it.
This now works:
```
$ make llvm-source
$ export LLVM_BUILDDIR=~/stuff
$ make ~/stuff  # instead of make llvm-build
$ make
```
The existing approach (`make llvm-build`) is unchanged by this PR.

Makefile: using an alternative LLVM build dir now works

---

version.go

This should be merged before all the other PRs.

main: update version to 0.8.0-dev

---

README.md

Based on the website https://webassembly.org.

Update README.md; correct Wasm case

---

src/examples/wasm/README.md

Modify instructions for running the wasm example HTTP server to `go run server.go`

Update examples/wasm README.md

---

compiler/compiler.go
main.go

Should be pretty straight forward. :smile:

main: fix outdated panic option text

---

compiler/compiler.go
compiler/gc.go
src/machine/i2c.go
src/machine/machine_generic.go
src/machine/spi.go
src/os/file_other.go
src/os/file_unix.go
src/runtime/arch_arm.go
src/runtime/baremetal.go
src/runtime/gc_globals_conservative.go
src/runtime/gc_globals_precise.go
src/runtime/gc_stack_portable.go
src/runtime/gc_stack_raw.go
src/runtime/runtime_unix.go
src/syscall/syscall_baremetal.go
src/syscall/tables_baremetal.go
targets/avr.json
targets/cortex-m.json
targets/riscv.json

This should simplify adding new baremetal targets (like the GameBoy Advance).

all: use baremetal build tag

---

compiler/syscall.go

This allows `go test` to work when running on a 32-bit machine. I haven't quite figured out how to test it using `GOARCH=386` on a non-32-bit machine though.

Add support for linux/386 syscalls.

---

Makefile
src/examples/gba-display/gba-display.go
src/machine/machine_gameboyadvance.go
src/runtime/runtime_arm7tdmi.go
targets/gameboy-advance.json
targets/gameboy-advance.ld
targets/gameboy-advance.s

Only tested in an emulator (mGBA and VisualBoyAdvance). Almost nothing is supported, but drawing to the screen works.

gameboy-advance: add initial support for this device

---

target.go

Note that there are other issues with Go 1.13 that I have yet to investigate. This just fixes the obvious one in the version parsing.
Fixes #458.

Fix parsing of beta Go versions.

---

compiler/compiler.go
src/runtime/string.go
testdata/string.go
testdata/string.txt

This is used by a few packages in the standard library, at least
compress/gzip and regexp/syntax.

compiler,runtime: implement []rune to string conversion

---

compiler/interface.go
compiler/reflect.go
src/reflect/sidetables.go
src/reflect/type.go
src/reflect/value.go
src/runtime/interface.go
testdata/reflect.go
testdata/reflect.txt

reflect: implement support for array types

---

src/runtime/arch_386.go
src/runtime/arch_amd64.go
src/runtime/arch_arm.go
src/runtime/arch_arm64.go
src/runtime/arch_avr.go
src/runtime/arch_wasm.go
src/runtime/gc_conservative.go
src/runtime/gc_stack_raw.go
src/runtime/runtime_arm7tdmi.go
src/runtime/scheduler_coroutines.go
src/runtime/scheduler_tasks.go

This is a series of commits to first clean up some stuff and then fix the actual bug (third commit).

Fix bug in GC caused by the new scheduler

---

compiler/check.go
compiler/compiler.go
compiler/defer.go
compiler/func-lowering.go
compiler/gc.go
compiler/goroutine.go
compiler/interface-lowering.go
compiler/interface.go
compiler/optimizer.go
compiler/syscall.go
main.go
main_test.go

I went through the code, and fixed every LLVM assertion that panicked in the main tests.

Fix bugs found by LLVM assertions

---

src/runtime/runtime_atsamd51.go

This PR sets the minimum sleep on SAMD51 based processors to 260us due to minimum delay in register synchronization
This corrects a similar problem to that of #526 except it affects the SAMD51 family of microcontrollers.

runtime/samd51: set minimum sleep to 260us

---

.circleci/config.yml

ci: add caching to macOS build

---

CHANGELOG.md
version.go

It's long past time for a new release!

main: version 0.8.0

---

compiler/symbol.go

This is sometimes needed for globals. For example, the atsamd21 chip requires the DMA buffers to be aligned on a 16 byte boundary.

compiler: add //go:align pragma

---

src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go

On my machine, I get a timeout during control packet rx and it crashes the microcontroller

raise timeouts on USB on atsamd and fix slice sizing

---

tools/gen-device-svd.py

This PR modifies the device wrapper generator so it can handle fields that use the `bitRange` element. It also ensures starting capital letters for attributes that are not already capitalized or start with a number from the generated wrappers so that they are properly exported for use from other packages.

generator: handle fields that use bitRange element and ensure fields exported

---

compiler/goroutine-lowering.go
compiler/llvm.go

When updating goroutine lowering, it appears that I made a few mistakes. This resulted in two bugs:
1. Each async function that called other async functions that had a return value would use a single buffer for return values. This buffer was sized to fit the return value of the first async call. Therefore if the function later called a function with a larger return value, the latter callee would write past the end of the buffer. This could cause data corruption, a segfault, or other undesired behavior.
2. When inserting a non-void return reactivation that is not an asynchronous tail yield, goroutine lowering emitted an instruction that attempted to return an undefined void value. The `undef void` neither makes sense nor is the correct type for the return, so this caused an LLVM error.
The …

Fix goroutine-lowering type errors

---

version.go

Following the example set by #572.

main: switch to version 0.10.0-dev

---

src/machine/machine_atsamd21g18.go

This PR corrects handling of pins > 32 based on bugfix for samd51 submitted by @Infinoid

machine/samd21: correct handling of pins > 32

---

interp/scan.go
interp/scan_test.go
interp/testdata/scan.ll

I was trying to fix #627 but it turned out to be harder than expected. While doing that, I added some more testing to the interp package which is what this PR is about.

interp: add testing for scanning for side effects

---

.circleci/config.yml
Makefile
compileopts/config.go
compileopts/options.go
compileopts/target.go
compileopts/target_test.go
compiler/compiler.go
compiler/func.go
compiler/gc.go
compiler/goroutine-lowering.go
compiler/goroutine.go
compiler/interface.go
compiler/optimizer.go
compiler/syscall.go
main.go
main_test.go
paths.go

This is a large refactoring PR, split into multiple pieces to make it easier to review. The first three commits just move things around, the last commit actually changes anything.
It should not affect any build. If it does, that's a bug.

Refactor compile options

---

interp/scan.go
interp/scan_test.go
interp/testdata/scan.ll

This gets a few more packages to compile, and should hopefully fix the issue with #686.

Fix "todo: store" panics

---

src/runtime/interface.go
testdata/interface.go

Improved version of https://github.com/tinygo-org/tinygo/pull/569, fixing a bug and adding/enabling tests.
closes #569

runtime: implement interface equality

---

cgo/libclang.go
cgo/testdata/types.go
cgo/testdata/types.out.go
testdata/cgo/main.go
testdata/cgo/main.h

This PR depends on #701. The real commit is the second one, which is just a few lines (by far the most is testing).

cgo: add support for nested structs and unions

---

Makefile
targets/nrf52-s132v6.json
targets/nrf52-s132v6.ld
targets/nrf52.json
targets/pca10040-s132v6.json

nrf: add support for SoftDevices to PCA10040 board

---

builder/env.go

The header detection code failed way too easily, bailing out when there was more than one Clang version directory.
This fixes the following problem in LLVM 9 on Debian:
testdata/cgo/main.h:1:10: fatal: 'stdbool.h' file not found
testdata/cgo/main.go:5:10: note: in file included from testdata/cgo/main.go!cgo.c:3:
On my system, this was the cause for the error (more than one version). Only the `9.0.1` directory contains the header files:
```
$ ls -l /usr/lib/llvm-9/lib/clang/
total 0
drwxr-xr-x 1 root root  6 okt 27 14:40 9/
drwxr-xr-x 1 root root 36 nov  9 17:23 9.0.0/
drwxr-xr-x 1 root root 30 okt 27 14:40 9.0.1/
```

builder: make Clang header detection more robust

---

compiler/optimizer.go
transform/panic.go
transform/panic_test.go
transform/testdata/panic.ll
transform/testdata/panic.out.ll

This moves the transformation pass to the right location, and adds tests to see that it actually works correctly.

compiler: move ReplacePanicsWithTrap pass to transforms

---

.circleci/config.yml
Dockerfile
Makefile
azure-pipelines.yml
builder/commands.go
builder/env.go
cgo/libclang.go
cgo/libclang_config.go
cgo/libclang_stubs.c
go.mod
go.sum

This will probably require some compiler changes.

all: switch to LLVM 9

---

CHANGELOG.md
version.go

main: version 0.10.0

---

Makefile
src/machine/board_atsamd21.go
src/machine/board_circuitplay_express.go
src/machine/board_circuitplay_express_baremetal.go
src/machine/machine_atsamd21.go

This requires a number of changes to atsamd21 code. It's not a very clean separation, but I couldn't come up with a better one.

targets: simulate Circuit Playground Express in play.tinygo.org

---

src/machine/board_arduino_nano33.go
src/machine/board_arduino_nano33_baremetal.go
src/machine/board_atsamd21.go

machine: support arduino-nano33 on play.tinygo.org

---

main.go

This PR searches for a reasonable default port value on macOS based on the typical serial port naming, so that if a single Arduino Nano33 is plugged into a Mac, the developer does not have to search for the correct port and enter it manually.
Before this PR:
```
ls /dev | grep usb
export NANO33_DEV_PATH=/dev/{YOUR TTY USBMODEM ID}
tinygo flash -target arduino-nano33 -port=$NANO33_DEV_PATH examples/blinky1
```
With this PR:
```
tinygo flash -target arduino-nano33 examples/blinky1
```

flash: search for default serial port on macOS

---

tools/gen-device-svd/gen-device-svd.go

This simplifies the code. The fields are blank anyway so there is no way to access them anyway (volatile or not).
Also do some other related simplifications of the code that result from this change.
I tested this by comparing all smoketests (from the compiler and from all drivers) to check whether the outputs are the same. That way, I found and fixed some bugs. After this, the only test case that has a different output is (again!) examples/apa102 from the drivers repo - and again in reflection data, not in any suspicious code.

tools: use byte padding to skip unused register ranges

---

compiler/goroutine-lowering.go

Depends on #788. Should improve "async function foo used as function pointer" like errors.

 compiler: improve error locations in goroutine lowering 

---

CHANGELOG.md
version.go

main: version 0.11.0

---

version.go

This PR increments version to 0.12.0-dev
'nuff said!

main: increment version to 0.12-dev

---

compiler/interface.go
testdata/interface.go

compiler: fix assertion on empty interface

---

main_test.go

Sometimes, tests suddenly hang somewhere (in particular in emulators
where crashes often lead to hangs). Setting a limit has two advantages:
1. Quickly killing test processes that are frozen (as opposed to waiting for the default 10min go test timeout).
2. The output becomes visible, hopefully giving a clue what went wrong.

main: kill tests if they run too long

---

.circleci/config.yml
compileopts/target.go
compiler/symbol.go
main_test.go

This is a collection of changes that makes every test run on all supported platforms.

Run all tests everywhere

---

main.go

This PR remove default port check for Digispark as micronucleus communicates directly using HID. 
In the current release, running `tinygo flash` using  `-target digispark` results in error "unable to locate a USB device to be flashed".

flash: remove default port check for Digispark

---

Makefile
src/machine/board_arduino_nano.go
targets/arduino-nano.json
targets/arduino.json
targets/atmega328p.json

Completely untested apart from that the Uno still works.
@alankrantas can you test this PR? I don't have a Nano.

all: add Arduino Nano support

---

main.go

This way it is possible to determine the source of an error when it happens.

main: differentiate between various serial/USB error messages

---

Makefile
src/machine/machine_fe310.go
src/runtime/interrupt/interrupt.go
src/runtime/interrupt/interrupt_hwvector.go
src/runtime/interrupt/interrupt_sifive.go
src/runtime/runtime_fe310.go
tools/gen-device-svd/gen-device-svd.go
transform/interrupt.go
transform/llvm.go

This PR implements interrupts for the RISC-V PLIC and uses this for UART interrupts. With this PR, the echo example works without modification.

RISC-V external interrupts

---

targets/wasm_exec.js

targets/wasm: update wasm_exec.js for go 1.13

---

version.go

This PR updates the tinygo version to the current dev version. Better late then never!

main: increment version to 0.13.0-dev

---

main.go

This makes fixes like https://github.com/tinygo-org/tinygo/pull/915 easier to apply (and in fact fixes a similar issue with the mgba debugger support). And in general, avoiding duplication is a good thing.
I tested this on the GBA, microbit, pca10040, cortex-m-qemu, hifive1b, and host targets.

main: move some duplicate code to a single place

---

builder/build.go
compiler/compiler.go
transform/globals.go
transform/globals_test.go
transform/testdata/globals-function-sections.ll
transform/testdata/globals-function-sections.out.ll
transform/testdata/globals-non-const.ll
transform/testdata/globals-non-const.out.ll

These two commits move two small passes to the transform package, and add tests. It is in preparation for #746, which is now almost finished.

Move small passes

---

LICENSE

This PR updates the license year to include 2020. No other changes.

license: update license year for 2020. No other changes.

---

targets/wasm_exec.js

This ports over the following three commits:
https://github.com/golang/go/commit/9627180f0f1f016307f4987cec6594baf90d64ae
https://github.com/golang/go/commit/aff2f6ece896e0fe76a2c8853abf868f689006f0
https://github.com/golang/go/commit/42b79f08239216eeea3cc1b0febc992f91bd88de
https://github.com/golang/go/commit/ecba83520d4c34870e0f5f0997d59d4496957240
This is the easy stuff, with what should be no effect on existing results.

wasm_exec: Sync polyfills with Go 1.14.1.

---

src/sync/map.go

This is a very simple implementation, just enough to get packages to compile.

sync: implement sync.Map

---

compiler/compiler.go

This is a very common case. Avoiding a `runtime.interfaceEqual` call leads to a very big reduction in code size in some cases (while it doesn't affect many other examples). A number of driver smoke tests are reduced by about 4kB just with this optimization.
I found this issue while looking into automatically calculating the required amount of stack space for goroutines. The `runtime.interfaceEqual` function is recursive, so it is best avoided.

compiler: optimize comparing interface values against nil

---

src/machine/machine_atsamd51.go

This saves about 112 bytes in flash and 288 bytes in RAM when the UART is not used.

machine/atsamd21,atsamd51: switch to modern interrupt registration method for UART

---

transform/coroutines.go

The coroutine lowering pass had issues where it iterated over maps, sometimes resulting in non-deterministic output. This change removes many of the maps and ensures that the transformations are deterministic.

transform (coroutines): remove map iteration from coroutine lowering pass

---

compiler/llvm.go

compiler/llvm.go: fix typo

---

CHANGELOG.md
version.go

This release fixes a few bugs introduced in the previous 0.13.0 release.

main: version 0.13.1

---

compiler/compiler.go
compiler/inlineasm.go
src/device/arm/arm.go
src/device/avr/avr.go
src/device/riscv/riscv.go
src/runtime/arch_arm.go
src/runtime/arch_cortexm.go
src/runtime/arch_tinygoriscv.go

This finally fixes a TODO left in the code.

arm: allow nesting in DisableInterrupts and EnableInterrupts 

---

main.go

flash: fix getDefaultPort() fails on Windows locales such as Japan
