src/machine/machine_avr.go

The register to be used for operations on AVR pins 0-7 should be `PORTD` not `PORTB`. This PR fixes this to use the correct register, was probably a copy and paste error.

avr: correct register for Set() operation on pins 0-7

---

src/machine/machine_avr.go
src/runtime/runtime_avr.go
src/runtime/runtime_nrf.go

Remove lots of board-specific configuration from the runtime.
Consequences:
* New boards are much easier to support, with less hacks. This will make #27 and #30 easier.
* The machine package won't be able to import the runtime package because circular dependencies are not allowed in Go. However, there are ways to hack around this (even the Go standard library does that).
* Code size is increased for very small programs that don't use the machine package (for example, examples/serial). I think this is because of the interrupts. However, most bigger programs will be using the machine package anyway so there is no real cost in practice.
* Code size is roughly the same (+2 for AVR) or even reduced (-32 for NRF) for programs that do use the machine module, like examples/echo.
All in all, I …

Let the runtime use machine.UART0

---

compiler/optimizer.go

This commit implements a few optimizations that are relevant for the echo example (and some others):
1. Some extra LLVM optimization passes that are important for Go code.
2. A simple heap-to-stack transformation that checks whether a given allocated pointer escapes. If it doesn't, it is stack allocated instead of heap allocated.
3. A pass that optimizes the `[]byte("foo")` pattern, as long as the resulting byte slice is never written to.
Together, these optimizations result in somewhat reduced code size:
board | .text before | .text after | change
--- | --- | --- | ---
Arduino | 1484 |  1298 | -186
micro:bit | 1592 | 1512 | -80
pca10040 | 2072 | 1992 | -80
The code for blinkm is also reduced in size.
But of course, avoiding heap allocation is often more important than code size so I'm …

WIP: Optimize heap allocations

---

Dockerfile

The Dockerfile was missing the part where we download
the dependencies into the vendor folder. It was of course
working locally because I had a vendor folder already.

Add vendor step to Dockerfile

---

Dockerfile

When building, `tinygo` needs access to files relative to the directory it was built from. Include `src` and `targets` directories.

Dockerfile: include necessary build subfolders

---

main.go

This enables project to conditionally skip code that can't compile on tinygo.

tinygo: add 'tinygo' build tag

---

Gopkg.lock
Makefile
compiler/compiler.go
interp/README.md
interp/errors.go
interp/frame.go
interp/interp.go
interp/scan.go
interp/utils.go
interp/values.go
main.go
main_test.go
testdata/init.go
testdata/init.txt

Add a new method of interpretation, which works directly on LLVM IR. When finished, this should make interpretation more correct while at the same time providing more optimization opportunities.
When this is finished, I hope that #53 will be easier to implement correctly. Also, this should make #56 be a non-issue.

WIP: interpret LLVM IR instead of Go SSA

---

src/runtime/arch_tinygoarm.go
src/runtime/arch_wasm.go
src/runtime/override_js.go
src/runtime/runtime_tinygoarm.go
src/runtime/runtime_wasm.go
targets/bluepill.json
targets/microbit.json
targets/nrf52840-mdk.json
targets/pca10040.json
targets/qemu.json

Let the standard library think that it is compiling for js/wasm.
The most correct way of supporting bare metal Cortex-M targets would be
using the 'arm' build tag and specifying no OS or an 'undefined' OS
(perhaps GOOS=noos?). However, there is no build tag for specifying no
OS at all, the closest possible is GOOS=js which makes very few
assumptions.
Sadly GOOS=js also makes some assumptions: it assumes to be running with
GOARCH=wasm. This would not be such a problem, just add js, wasm and arm
as build tags. However, having two GOARCH build tags leads to an error
in internal/cpu: it defines variables for both architectures which then
conflict.
To work around these problems, the 'arm' target has been renamed to
'tinygo.arm', which should work around these problems. In the future, a …

all: rename 'arm' to 'tinygo.arm' for Cortex-M

---

src/examples/blinkm/blinkm.go
src/machine/i2c.go
src/machine/machine_avr.go
src/machine/machine_nrf.go

Rewrite of the I2C interface. This interface supports more features and is compatible across nRF and AVR.
AVR support and the blinkm example have not been tested.
@deadprogram what do you think of this? It presents a simpler interface for I2C that is more compatible with regular I2C devices.
```go
type I2C interface {
Start(address uint8, write bool)
Stop()
ReadByte() byte
WriteByte(byte)
Read(buf []byte) // TODO: io.Reader compatibility
Write(buf []byte) // TODO: io.Writer compatibility
ReadRegister(address uint8, register uint8, data []byte)
WriteRegister(address uint8, register uint8, data []byte)
}
```

machine: redesign I2C interface

---

compiler/compiler.go
compiler/interface-lowering.go
compiler/interface.go
compiler/optimizer.go
interp/frame.go
interp/scan.go
ir/interpreter.go
ir/ir.go
ir/passes.go
main.go
src/runtime/interface.go
src/runtime/print.go
testdata/interface.go

This PR is not finished yet but I made a PR to show what's coming. Generated code for interfaces has become much smaller:
```
testdata/interface.go before:
code    data     bss |   flash     ram 
3560       8    2132 |    3568    2140
testdata/interface.go after:
code    data     bss |   flash     ram 
3016       8    2132 |    3024    2140
```

Interface rewrite

---

src/machine/board_pca10056.go
src/machine/machine_nrf52840.go

Add support for ADC and PWM interfaces on nrf52840 based boards, such as the pca10056 and reel board.

machine/nrf52840: add support for ADC and PWM interfaces

---

compiler/compiler.go
compiler/defer.go
src/runtime/defer.go

Implement defer in a different way, which results in smaller binaries. The binary produced from testdata/calls.go (the only test case with defer) is reduced a bit in size, but the savings in bytes greatly vary by architecture:
```
Cortex-M0:    -96 .text / flash
WebAssembly: -215 entire file
Linux x64:    -32 .text
```
Deferred functions in TinyGo were implemented by creating a linked list of struct objects that contain a function pointer to a thunk, a pointer to the next object, and a list of parameters. When it was time to run deferred functions, a helper runtime function called each function pointer (the thunk) with the struct pointer as a parameter. This thunk would then in turn extract the saved function parameter from the struct and call the real function.
What this commit changes, …

compiler: avoid function pointers in defer calls

---

compiler/calls.go
compiler/compiler.go
compiler/defer.go
compiler/interface.go
docs/internals.rst
interp/interp.go
ir/ir.go
ir/passes.go
src/runtime/defer.go
src/runtime/panic.go
src/runtime/runtime_unix.go
src/runtime/runtime_wasm.go
src/runtime/scheduler.go

Depends on #100.
This simplifies the compiler a lot and avoids lots of tricky edge cases that are rarely tested. Resulting binary size is unchanged on Linux/x86 and Cortex-M0 and is slightly increased in WebAssembly. The increase in binary size in WebAssembly is probably because of the strict requirements on the number of parameters in function calls.
@deadprogram

compiler: always use fat function pointers with context

---

.travis.yml
Dockerfile
Makefile
compiler/compiler.go
ir/ir.go
loader/cgo.go
loader/errors.go
loader/libclang-cfuncs.go
loader/libclang.go
loader/loader.go
loader/ssa.go
main.go
main_test.go
target.go
targets/wasm.json
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

We were using `golang.org/x/tools/go/loader`, but there are lots of limitations with that for TinyGo. One in particular is that it is not possible to get loaded .c files (etc.) to be include with the program. Also, it looks like `golang.org/x/tools/go/loader` is being deprecated in favor of `golang.org/x/tools/go/packages`, which has even more problems.
By using our own loader, it is possible to support more advanced features in the future like special import paths and doing incremental compilation by loading type information from existing object files. Right now it makes it possible to write our own Cgo implementation.

WIP: new package loader

---

compiler/compiler.go
main.go
target.go
targets/arduino.json
targets/digispark.json

This PR reduces code size by ~7% on atmega328p simply by specifying the target CPU name. Apparently, without it LLVM falls back to a lowest-common-denominator CPU.
I got this idea after talking with @Rahix about bugs in the AVR backend of LLVM.
@deadprogram what do you think? I have tested both blinky on the Uno and Digispark and tested the (more complex) echo example on the Uno.

Reduce code size for AVR

---

compiler/compiler.go
main.go
src/runtime/arch_386.go
src/runtime/arch_arm.go
src/runtime/arch_arm64.go
target.go
targets/avr.json
targets/cortex-m.json

This commit does two things:
* It adds support for the GOOS and GOARCH environment variables. They
fall back to runtime.GO* only when not available.
* It adds support for 3 new architectures: 386, arm, and arm64. For
now, this is Linux-only.
@deadprogram?

all: add support for more architectures and GOOS/GOARCH

---

tools/gen-device-avr.py
tools/gen-device-svd.py

In many cases python3 may not be in /usr/bin, /usr/bin/env is SUS portable alternative to using explicit path.

tools: use env to search path for python3

---

src/runtime/string.go

This PR adds implementation of `strings.IndexByte()` which resolves #154

runtime/strings: add implementation of strings.IndexByte()

---

src/examples/echo/echo.go
src/machine/board_arduino.go
src/machine/board_itsybitsy-m0.go
src/machine/buffer.go
src/machine/machine_atmega.go
src/machine/machine_atsamd21g18.go
src/machine/machine_attiny.go
src/machine/machine_avr.go
src/machine/machine_nrf.go
src/machine/machine_stm32f103xx.go
src/machine/uart.go
src/runtime/runtime_atsamd21g18.go

This PR add the core support for allowing multiple UARTs at the same time for those devices that have more than one. This PR only adds the actual implementation for multiple UARTs for the SAMD21. Other boards still have `UART0` but using this new core.

Add core support for multiple UARTs

---

Dockerfile

Currently, if the user hasn't run
`git submodule update --init` beforehand, the docker build will fail
This little addition makes the build atomic and ready for automatic CI tests for the future

making Docker build resilient

---

.travis.yml
compiler/syscall.go
main_test.go
target.go

This commit
1. Adds syscall support for two architectures: arm and arm64.
2. Adds testing support by running binaries using qemu-arm.

Add syscall support for arm and arm64 + testing

---

CONTRIBUTING.md
README.md

This PR refactors README.md to avoid duplication with information already on the web site, and to reorder to make it easier for new users. It also moves a few details over to the CONTRIBUTING.md document.

docs: refactor README content

---

main.go
version.go

This PR adds a `tinygo version` subcommand to display the current version of the TinyGo compiler:
```shell
tinygo version
TinyGo compiler v0.1.0
```
The same info is displayed alongside the usage info.

Add tinygo version subcommand

---

.travis.yml

This PR displays the output file sizes for target smoke test builds on Travis, as a simple way we can determine if the build sizes are changing, and just general informational purposes.

build: display output file sizes for target smoke test builds on Travis

---

Gopkg.lock
ir/ir.go
loader/cgo.go
loader/libclang.go
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

Global variables (like functions) must be declared in the import "C"
preamble and can then be used from Go.

loader: support global variables in CGo

---

compiler/compiler.go
ir/ir.go
loader/cgo.go
loader/libclang.go
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

This builds upon #173. It adds support for pointer types and function pointer types in CGo.

cgo: add pointer types

---

src/machine/board_microbit.go

Added the rest of the pins in case you are using a breakout/expansion board

Added regular pins const for bbc:microbit

---

compiler/compiler.go
compiler/interface.go
loader/libclang.go
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

Note that the first commit changes how `complex64` and `complex128` types are implemented, so that they follow how complex numbers are implemented in Clang and are specified by C11. Before this, they were implemented as a vector of two float types, which seemed to get a bigger alignment (up to 16 bytes) on amd64.
Code size was unchanged on amd64.

Add floating point support to CGo

---

Makefile

If you try to run `make tinygo` after running `make clean` you get the following error:
```shell
make: *** No rule to make target 'build/tinygo', needed by 'tinygo'.  Stop.
```
This very small change corrects that issue.

build: correct Makefile to build tinygo executable correctly

---

.travis.yml
Gopkg.lock
compiler/compiler.go
compiler/syscall.go
loader/libclang_config.go
main.go
main_test.go
src/os/file_unix.go
src/runtime/os_darwin.go
src/runtime/runtime_unix.go
target.go

WARNING: this PR depends on https://github.com/tinygo-org/go-llvm/pull/3, and after that one is merged `dep` should be run again to update the branch etc.
This PR adds macOS support, and automatically tests its support in Travis. I needed to disable linux/arm and linux/aarch64 tests in macOS because it tries to use the GNU toolchains, but that support is tested in Linux anyway so there is no big loss.

all: add macOS support

---

main.go

This PR addresses #142 by extending the `tinygo flash` command to support different output file types based on contents of flash key in target file.
For example, the target file `microbit.json`
```json
"flash": "openocd -f interface/cmsis-dap.cfg -f target/nrf51.cfg -c 'program {hex} reset exit'",
```
will continue to compile a `.hex` file becase the token in the `flash` key is `{hex}`.
Modifying the target file `itsybitsy-m0.json` like this:
```json
"flash": "uf2conv.py {bin}"
```
will compile a `.bin` file before trying to execute the flashing command.

compiler: extend flash command to support different output file types

---

src/runtime/runtime_atsamd21.go

This PR corrects the calculation for the runtime `ticks()` function so that go routine scheduling can function as expected as described in issue #149

machine/samd21: correct calculation for runtime ticks() function

---

src/machine/board_itsybitsy-m0.go
src/machine/machine_atsamd21.go

Now that port B is available, define them. Also, define all hardware pins for easy access (e.g. `PB23` instead of `55`).

samd21: define and use hardware pin numbers

---

src/device/arm/arm.go

These intrinsics aren't complete yet. Perhaps I should make them complete, but that will require some more compiler support. But I think they're useful as-is, to be made more complete in the future.

arm: provide intrinsics to disable/enable interrupts

---

src/machine/machine_nrf51.go
src/machine/machine_nrf52.go
src/machine/machine_nrf52840.go

I have some refactorings in mind for the ws2812 driver, but it requires these definitions. The plan is to select the driver implementation by a switch on the frequency, not compile-time on the board name. This switch should be easily optimized away but enables more flexibility in the driver (for example, all samd21 boards would be automatically supported).

nrf: add CPU frequency

---

src/machine/machine_atsamd21.go

This PR adds GPIO_INPUT_PULLUP and GPIO_INPUT_PULLDOWN GPIO pin config options for the ATSAMD21 family of boards.

machine/atsamd21: add GPIO_INPUT_PULLUP and GPIO_INPUT_PULLDOWN options

---

src/machine/board_circuitplay_express.go
targets/circuitplay-express.json

This PR adds basic support/pin mappings for the Adafruit Circuit Playground express ATSAMD21 board.

machine/circuitplay_express: add basic support for Adafruit Circuit Playground express

---

src/runtime/runtime_atsamd21.go

This PR initializes all of the ATSAMD21 SERCOM clocks at one time, to simplify the various board variants that use the same SERCOM peripherals but for different purposes.

machine/samd21: init all SERCOM clocks to better handle board variants

---

src/machine/machine_atsamd21.go

This PR corrects the ATSAMD21 get/setPinCfg and get/setPMux functions for PORTB pins. The initial implementation was incorrect, it has the order reversed.

machine/samd21: correct get/setPinCfg and get/setPMux functions for PORTB

---

src/machine/board_circuitplay_express.go
src/machine/board_itsybitsy-m0.go
src/machine/machine_atsamd21.go

This PR move definitions for I2C interfaces into board files, since pin connections on each SAMD21-based board implementation can differ between boards.

machine/samd21: move definitions for I2C interfaces into board files

---

Gopkg.lock
main.go
objcopy.go
target.go
targets/avr.json
targets/cortex-m.json

This lessens the dependency on binutils (e.g. arm-none-eabi-objcopy).
Tested on a few devices (digispark, pca10040, Playground Express), but some more testing would be useful.

all: use internal objcopy implementation

---

.circleci/config.yml
.travis.yml
README.md

End goal: replace Travis CI with CircleCI. CircleCI is much faster and doesn't have an uncertain future like Travis CI.
For now, let's just replace the Linux tests with CircleCI.

circleci: replace Linux tests on Travis CI with CircleCI

---

src/machine/board_circuitplay_express.go
src/machine/board_itsybitsy-m0.go
src/machine/machine_atsamd21.go
src/machine/spi.go

This PR implements the SPI interface for the currently supported SAMD21 boards which are the ItsyBitsy-M0 and the Circuit Playground Express.

machine/samd21: implement SPI interface for currently supported SAMD21 boards

---

compiler/compiler.go
src/runtime/panic.go
testdata/slice.go

Previously, this would have resulted in a LLVM verification error because runtime.sliceBoundsCheckMake would not accept 64-bit integers on these platforms.
TODO before merging: add tests.

compiler: fix make([]T, ...) with big integers on 32-bit systems or less

---

compiler/compiler.go
compiler/interface-lowering.go
compiler/interface.go
src/runtime/interface.go

In LLVM 8, the AVR backend has moved all function pointers to address space 1 by default. Much of the code still assumes function pointers live in address space 0, leading to assertion failures.
This commit fixes this problem by autodetecting function pointers and avoiding them in interface pseudo-calls.

compiler: support function pointers outside of addrspace 0

---

main_test.go

The WebAssembly target is not yet considered stable in LLVM 7, but has
been enabled in the Debian builds so tests can run on Debian. However,
the Homebrew builds don't have it enabled which results in test
failures.
Temporarily run WebAssembly tests only on Linux to fix this. This can be
reverted after a switch to LLVM 8, which has WebAssembly enabled by
default.

main: only run WebAssembly tests on Linux

---

compiler/asserts.go
compiler/compiler.go
interp/frame.go
interp/interp.go
interp/values.go
src/runtime/panic.go

Make sure we never dereference a nil pointer without panic. The code size impact is around 5%, but I think the added safety (and Go language spec compliance!) is worth it. We can eliminate most of this for systems with MMU (Linux etc.) if needed.
The first commit also refactors the interp package and eliminates lots of repetitive code but does not affect the generated code. It makes the second commit easier to implement.
Fixes #180.

Implement nil checks

---

compiler/asserts.go
compiler/compiler.go
src/runtime/panic.go

Depends on #222.
This PR improves slice/string/array bounds checking by inlining the checks. This has the result of reduced code size of around 1% and likely increased performance as well.
Unfortunately, LLVM is not smart enough to do bounds check elimination even in trivial cases like iterating over a slice. This should be added in the future to reduce code size even further (up to around 1%).

Improve bounds checking

---

objcopy.go
uf2.go

The function extracting the firmware image for .hex and .bin files wasn't working correctly: it only extracted the .text segment and not the .data segment.
This commit fixes this issue, so that it behaves (hopefully) just like `objcopy -O{ihex|binary}`.
Another small change is that the formatting of the .hex file was made more like the output of objcopy: no entry addres (old Intel CPU holdover) and 16 bytes of data on each line.

main: include .data section in .hex file

---

compiler/compiler.go
compiler/goroutine-lowering.go
interp/frame.go
interp/scan.go
src/reflect/value.go
src/runtime/chan.go
src/runtime/runtime.go
src/runtime/runtime_wasm.go
testdata/channel.go
testdata/channel.txt

This PR contains almost all changes of #211, but leaves out testing on Go 1.12 because bare-metal targets are not yet supported.
This PR is still useful, because it supports the updated syscall/js package used in the WebAssembly target. Go 1.11 is still supported.
fixes #216

Support Go 1.12 for most targets

---

.circleci/config.yml

This is not necessary anymore since d6c2d6e301: llvm-ar has been replaced with llvm-ar-8. It will speed up CircleCI tests a tiny bit.

circleci: don't install the llvm package

---

compiler/optimizer.go

The icmp instruction is often used in nil checks, so this instruction
happens very frequently now that TinyGo automatically inserts nil checks
everywhere. Escape analysis would conservatively mark such pointers as
escaping, which they obviously don't.
This commit improves escape analysis to allow icmp instructions.
---
I found this optimization opportunity while working on #249. It reduces code size for the following test cases:
* testdata/map.go
* testdata/math.go
* testdata/print.go
* testdata/reflect.go
* testdata/stdlib.go
The savings aren't big but the biggest advantage of this is not code size reduction but avoiding heap allocations.

compiler: improve escape analysis to allow icmp

---

src/runtime/runtime_cortexm.go

This should improve the following issue:
https://github.com/tinygo-org/tinygo/issues/252

runtime: implement memmove intrinsic

---

.circleci/config.yml
Gopkg.lock

all: support Go 1.12

---

compiler/asserts.go
compiler/compiler.go
compiler/optimizer.go
src/runtime/panic.go

Some tests get bigger, most get smaller. However, all tested driver
examples get smaller in size showing that this is a good change in the
real world.

Fix escapes due to nil checks

---

.circleci/config.yml
.travis.yml
Dockerfile
commands_macos.go
main.go
targets/arm.ld
targets/cortex-m.json
targets/wasm.json

LLD version 8 has added support for armv6m: https://reviews.llvm.org/D55555
This means we can use LLD instead of `arm-none-eabi-ld`, eliminating our dependency on GNU binutils.
There are small differences in code size, but never more than a few bytes.
---
I have tested the following devices:
* nrf51 (microbit)
* nrf52 (pca10040)
* samd21 (circuitplay-express)
It all works perfectly in my tests.

arm: use the lld linker

---

.circleci/config.yml
Makefile

This PR is actually two commits, separated because they're somewhat separate:
* you can now run `make llvm-build` and it will download and build a local LLVM installation for use in `make static` or `make release`.
* CircleCI uses the above to build TinyGo statically on each build and provides a working (tested!) release tarball as part of it.
This should make it easier for people to build LLVM manually, and make releases a bit easier as amd64 builds can simply be downloaded from CircleCI.

Build release tarball as part of CircleCI tests

---

src/machine/board_itsybitsy-m0.go

This PR sets the pin and pin mode mapping for i2c0 bus on the Adafruit ItsyBitsy-M0 board.

machine/itsybitsy-m0: set pins and pin mode mapping for i2c0 bus

---

compiler/compiler.go
testdata/structs.go
testdata/structs.txt

This should finally fix the struct casting bug.
closes #162 
fixes #161

compiler: implement casting named structs and pointers to them

---

interp/frame.go

A call to .IsConstant() also returns true for constant globals, not just
constant expressions. Do an extra check that we're really operating on a
constant expression.

interp: fix segmentation fault in some builds

---

compiler/asserts.go
compiler/compiler.go
src/runtime/panic.go
src/runtime/print.go

This is a collection of bug fixes that together get testdata/stdlib.go to compile for AVR (at least to IR, compiling to machine code causes a crash in the backend). It also fixes a more serious (and subtle!) issue where it gets casting wrong when casting between signed and unsigned integers.

Fix uintptr handling for AVR

---

loader/cgo.go
loader/libclang.go
loader/loader.go

This makes CGo-emitted diagnostics very similar to regular errors emitted while parsing/typechecking a package, and thus more readable.
It's not perfect yet, but after introducing some errors in testdata/cgo, this is the resulting output:
testdata/cgo/main.h:18:11: error: a parameter list without types is only allowed in a function definition
testdata/cgo/main.go:5:10: note: in file included from testdata/cgo/main.go!cgo.c:2:
testdata/cgo/main.go:6:19: error: expected identifier or '('
Previously, this was the output:
/home/ayke/src/github.com/tinygo-org/tinygo/testdata/cgo/main.h:18:11: error: a parameter list without types is only allowed in a function definition
cgo-fake.c:3:19: error: expected identifier or '('
cgo: libclang cannot parse fragment

cgo: improve diagnostics

---

.circleci/config.yml
Gopkg.lock
builtins.go
commands.go
commands_macos.go

The ar file format is pretty simple and can be implemented by using a Go package. Use that instead of calling out to `llvm-ar`.
There are a few limitations to the used package, but that doesn't seem to matter for our use case (linking compiler-rt for use with `ld.lld`):
* no index is created
* long filenames are truncated
* no support for archives bigger than 4GB

 main: drop the dependency on llvm-ar

---

compiler/interface-lowering.go
compiler/interface.go
interp/frame.go
interp/scan.go
src/runtime/interface.go
testdata/stdlib.go
testdata/stdlib.txt

This adds support for the math/rand package.
There are small differences in code size when testing on a micro:bit: testdata/interface.go got slightly smaller and testdata/reflect.go got slightly bigger. testdata/stdlib.go also got slightly bigger but that's because it tests more: when removing the extra code the size is the same.

all: support interface asserts in interp

---

compiler/interface-lowering.go

It was removing some globals that still had uses left.
This bug was introduced by #277 but I didn't notice it because an optimization pass would hide it.

compiler: fix interface lowering pass

---

linker-builtin.go
linker-external.go
main.go

This commit adds the TinyGo root directory (`TINYGOROOT`) to the linker script `-L` search path, so that linker scripts can be found when running `tinygo` outside of the TinyGo root.
This was already working before when using an external linker by setting the working directory, but this is not possible when using the internal linker. However, by adding the root directory to the linker search path (`-L`), it can now find these linker scripts.
fixes #265

main: fix linker script includes when running outside TINYGOROOT

---

Makefile

This is just a small hint to users that may not know where the error is coming from.

Makefile: check whether LLVM was build before making a static binary

---

src/machine/board_itsybitsy-m0.go
src/machine/machine_atsamd21.go

This PR corrects pad/pin handling when using both UART and USBCDC interfaces at same time on SAMD21-based boards such as the ItsyBitsy-M0.

machine/atsamd21: correct pad/pin handling when using both UART and USBCDC

---

compiler/compiler.go
compiler/func-lowering.go
compiler/func.go
compiler/inlineasm.go
compiler/interface.go
compiler/optimizer.go
src/runtime/func.go

This PR refactors func value handling, making multiple implementations possible. It also eliminates all function pointers from the WebAssembly output, replacing them with numeric indices per function signature and a switch on them. This is very useful for goroutines lowered using LLVM coroutines, which don't support function pointers (yet).

Refactor function pointers

---

.circleci/config.yml
BUILDING.md
Makefile

This replaces the older way which just does the following:
go install .
and
go test -v .
Instead, `make` and `make test` will now build TinyGo statically linked against LLVM, so that `go install` and `go test -v` should be used manually.
(Warning: conflicts with #281 but it should be trivial to resolve).

Makefile: build static binaries only

---

src/examples/microbit-blink/microbit-blink.go

This PR adds a micro:bit blink example that uses the entire LED array. The reason for adding this to the built-in examples is really to provide a basic "hello, world" example for the very common micro:bit board.

examples: add microbit blink example

---

loader/libclang.go
loader/libclang_stubs.c

Sometimes when a GC happens while processing a C fragment with libclang, a pointer-typed integer with value 0x1 ends up on the Go stack and the GC will trip over it. This commit changes the offending struct type to be `uintptr_t` instead of `void*`.
See https://go-review.googlesource.com/c/go/+/66332 for a similar change.
This commit has been ported from #266.

loader/libclang: fix CGo-related crash

---

src/machine/machine_atsamd21.go

This PR corrects the readings from the ADC by selecting internal ground for the ADC and scale result correctly to 16-bit.

machine/atsamd21: select internal ground for ADC and scale result correctly

---

.circleci/config.yml
Makefile
compiler/compiler.go
loader/libclang.go
loader/libclang_stubs.c
loader/loader.go
main_test.go
targets/cortex-m.json
targets/wasm.json
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

Add support for header files bundled with the compiler by copying them into the release tarball.
This turned out to be a lot simpler than expected.

cgo: support builtin #include headers

---

compiler/compiler.go
compiler/optimizer.go
main.go

Currently defined: abort and trap. `-panic=unwind` should be implemented in the future.
This saves quite a bit in code size.

compiler: make panic configurable

---

compiler/calls.go
compiler/channel.go
compiler/compiler.go
compiler/defer.go
compiler/errors.go
compiler/func.go
compiler/inlineasm.go
compiler/interface.go
compiler/map.go
compiler/optimizer.go
compiler/syscall.go
main.go

This PR refactors error handling. The primary motivation is to be able to show multiple compiler errors to the user at the same time. For example, if you have this code:
```go
c64 := complex(f32, 1.2)
c64 += 2
c64 *= 2
c64 /= 2
println(c64)
```
Before this PR, it would result in the following error because these operations have not yet been implemented on complex numbers:
```
testdata/float.go:56:2: todo: binop on complex number: +
```
After this change, it will show all the errors:
```
testdata/float.go:56:2: todo: binop on complex number: +
testdata/float.go:57:2: todo: binop on complex number: *
testdata/float.go:58:2: todo: binop on complex number: /
```
But the main part of this PR (the first 3 commits) is a huge refactor of large parts of the compiler to make error handling much …

Refactor error handling

---

compiler/compiler.go
compiler/defer.go
compiler/goroutine-lowering.go

In Go, it is not possible to construct pointers that are out of bounds (and not null), so let LLVM know about this fact.
This leads to a significant code size reduction, around 3% in many cases.

compiler: mark all GEPs as inbounds

---

buildcache.go
builtins.go
main.go
main_test.go
targets/cortex-m.json
targets/wasm.json

A set of commits that improve portability to Windows. They do not add Windows support, but will be required if we add Windows support in the future.
For reference, this originally came from the appveyor branch, which adds some Windows support (but is not finished). These are the bits that seem to be an improvement in general.

Portability improvements

---

src/examples/wasm/main/main.go

The generated wasm is 575 bytes when compiled with -no-debug (and works), which is a much better first experience for new users than the 20KB+ added (atm) by including `fmt`. :smile:

wasm: use println instead of fmt

---

loader/cgo.go
loader/libclang.go
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

This PR includes two semi-related commits that improve support for Go types. The first one reworks support for elaborated types (struct, union), the second avoids having to support unused C types.

cgo: improve C types support

---

src/examples/wasm/README.md
src/examples/wasm/server.go

Also tells browsers not to cache things, which should help when people compile new versions of their wasm in the background (as per standard dev iteration).

examples: tell browsers to not cache wasm files from the example server

---

builtins.go
main.go
targets/nrf51.json
targets/nrf52.json
targets/nrf52840.json

This commit avoids setting the working directory to the TinyGo root when invocating Clang. This helps to weed out issues before we add support for bundling Clang in a release.
This commit helps #184.

main: do not set working directory for Clang invocation

---

compiler/compiler.go

When compiling a piece of code where a function value is called,
the compiler panics if the function value's type is a defined type,
and not just a type literal (function signature): The type assertion
(*types.Signature) fails, because the type of the func value is a
*types.Named.
This patch fixes this by using the type's underlying type, so that a
types.Named is properly turned into its underlying types.Signature,
before the type assertion takes place.
It takes advantage of the property that all types have an underlying type
(both are the same, if a type is not named).
Fixes #320

compiler: fix comp. of func calls for func values of a defined type

---

compiler/channel.go
compiler/compiler.go
compiler/goroutine-lowering.go
compiler/llvm.go
compiler/sizes.go
src/runtime/chan.go
src/runtime/scheduler.go
testdata/channel.go
testdata/channel.txt
testdata/coroutines.go
testdata/coroutines.txt

This is implemented as follows:
* The parent coroutine allocates space for the return value in its
frame and stores a pointer to this frame in the parent coroutine
handle.
* The child coroutine obtains the alloca from its parent using the
parent coroutine handle. It then stores the result value there.
* The parent value reads the data from the alloca on resumption.
The current implementation is not very efficient but it's a start.
Fixes #301.

compiler: support returning values from async functions

---

loader/libclang.go

Two commits cherry-picked from the softdevice branch that improve cgo error messages (but not in a very visible way).
The first one fixes a crash that happens in rare cases (not sure why), the second replaces a hack with a proper implementation.

CGo diagnostics

---

Dockerfile

This PR performs a hard submodule reset after having moved the git repo before continuing the docker build process.
EDIT: original technique did not work as expected, but a more brute force one did.

docker: perform a hard submodule reset after having moved the git repo

---

compiler/compiler.go
compiler/optimizer.go

Instead of assuming all declared (but not defined) functions are CGo
functions, mark all pointer params of externally visible symbols
'nocapture'. This means you may not store pointers between function
calls.
This is already the case when calling CGo functions upstream:
https://golang.org/cmd/cgo/#hdr-Passing_pointers
---
This is part of #285, because escape analysis would otherwise do incorrect things when compiling packages independently.

cgo: do not allow capturing of external/exported functions

---

compiler/compiler.go
loader/loader.go
main.go
target.go

Check various locations that $GOROOT may live, including the location of
the go binary. But make it possible to override this autodetection by
setting GOROOT manually as an environment variable.

main: make $GOROOT more robust and configurable

---

main.go

A quick fix for an issue I accidentally introduced in #294. Only one error encountered during parse/typecheck would be shown. With this fix, all of them are.

main: fix multiple errors being reported as one

---

.circleci/config.yml
Makefile

These two dependencies are optional but enabled by default when available. Disable them in the Makefile so that the `tinygo` binary is portable to systems that don't have them or have a different version (for example, Arch has a newer version of libcurses and thus libtinfo).

Makefile: avoid libtinfo and libz dependency of LLVM

---

.circleci/config.yml
src/examples/i2s/i2s.go
src/machine/board_circuitplay_express.go
src/machine/board_itsybitsy-m0.go
src/machine/i2s.go
src/machine/machine_atsamd21.go

This PR provides a very basic initial implementation for the I2S hardware interface tested on the Adafruit Circuit Playground Express. It is only known to work with the PDM microphone that is onboard the Circuit Playground Express, although it might work with other I2S devices.

machine/samd21: Initial implementation of I2S hardware interface

---

compiler/compiler.go
compiler/interface.go
compiler/llvm.go
compiler/map.go
src/runtime/hashmap.go
testdata/map.go
testdata/map.txt

Implement growing of hashmaps and setting the initial size. Necessary for `js.Func` support (#226), among others.

Hashmap improvements

---

compiler/calls.go
compiler/compiler.go
interp/frame.go
interp/interp.go
interp/scan.go
testdata/channel.go
testdata/channel.txt

Improve debug information (see commit). Also, implement comparing channel values (found while working on this).
```
This commit adds debug info to function arguments, so that in many cases
you can see them when compiling with less optimizations enabled.
Unfortunately, due to the way Go SSA works, it is hard to preserve them
in many cases.
Local variables are not yet saved.
Also, change the language type to C, to make sure lldb shows function
arguments. The previous language was Modula 3, apparently due to a
off-by-one error somewhere.
```

Improve debug info to show function arguments in stack traces

---

compiler/compiler.go
compiler/volatile.go
ir/ir.go
src/machine/machine_atmega.go
src/machine/machine_attiny.go
src/machine/machine_avr.go
src/runtime/runtime_atmega.go
src/runtime/volatile/volatile.go
tools/gen-device-avr.py

This replaces #325 with a better to use API.
I tested examples/blinky1 and examples/blinky2 on an Arduino Uno, and tested examples/blinky1 on a digispark. They all still work, but code size is significantly increased. I'll improve this PR to avoid that.

Refactor volatile operations (try 2)

---

Dockerfile

This PR changes the Dockerfile to not remove make from tinygo-dev docker image. Te purpose of this is to make it easier to run the CI build in the TinyGo drivers repo, which uses the tinygo-dev image.

docker: do not remove make from tinygo-dev docker image

---

cgo/cgo.go
cgo/libclang.go
cgo/libclang_stubs.c
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

This commit adds support for C enums (treated as Go constants) and improves cgo error reporting when cgo encounters a type it does not understand.

cgo: add support for enum types

---

compiler/asserts.go
interp/scan.go

This fixes a bug in interp so that new-style register accesses work correctly. Previously, this hit the error `interp: branch on a non-constant`.
Also added a small optimization that I found while working on this.

Fix issue with new-style volatile operations

---

src/device/arm/cortexm.s
src/runtime/runtime_cortexm.go
targets/cortex-m.json

This is very useful for debugging. It differentiates between a stack
overflow and other errors (because it's easy to see when a stack
overflow occurs) and prints the old stack pointer and program counter if
available.
This code was written to debug https://github.com/tinygo-org/tinygo/pull/359 but printing an error is useful in any case because otherwise the MCU is just stuck at a hard fault without any indication as to what exactly happened (or even that there was a hard fault).
Of course, it increases code size for baremetal ARM microcontrollers but I think the benefits outweigh the cost in almost all cases (if necessary, it can be turned off at high optimization settings).
Example error:
```
fatal error: stack overflow with sp=0x1fffffd8
```

arm: print an error when a HardFault occurs

---

go.mod
go.sum

Add required files for vgo support. The new vgo system defaults to on
since Go 1.13 so we should be prepared for that once the release hits.
It is also useful for testing Go 1.13 before the release.
it has been tested with `GO111MODULE=on` on 3 Go versions: 1.11, 1.12 and 1.13. This PR might allow us to drop support for dep in a future release because versioning is now directly supported in the toolchain.

all: add go.mod and go.sum files for vgo support

---

Makefile
src/machine/machine_stm32f103xx.go
src/machine/machine_stm32f407.go
src/runtime/runtime_stm32f103xx.go
src/runtime/runtime_stm32f407.go

This PR refactors all current STM32-based board implementations to use the new volatile package for register access.
Tested on my Bluepill board.

machine/stm32: refactor to use new volatile package

---

compiler/compiler.go
main.go
src/runtime/string.go
src/runtime/strings_go111.go
target.go
testdata/stdlib.go
testdata/stdlib.txt

`strings.IndexByte` used to be implemented in the runtime. Now it is implemented using a direct call to `internal/bytealg.IndexByte`. Fixes #351.
The real problem is of course https://github.com/golang/go/issues/31330.

compiler,runtime: fix multiple definitions of a single function

---

src/machine/machine_stm32f103xx.go

machine/stm32f103xx: fix i2c 2 byte read

---

commands.go

This avoids the need to correctly set $PATH if LLVM 8 has been installed using Homebrew.

main: add the absolute path to clang-8 etc. on macOS

---

targets/wasm.json

See the following bugs for more information:
https://bugs.llvm.org/show_bug.cgi?id=41508
https://bugs.llvm.org/show_bug.cgi?id=37064
This should be removed again when we switch to LLVM 9, it may have a very small (basically negligible) compile time cost.

wasm: fix wasm-ld hang

---

.circleci/config.yml

This also updates the LLVM build to include this commit:
https://github.com/llvm-mirror/llvm/commit/d519e424c503d2d2a723284664a509a6cd5401a8

ci: use go modules instead of dep

---

src/machine/machine_atmega.go
src/machine/machine_atsamd21.go
src/machine/machine_avr.go
src/machine/machine_stm32f103xx.go
src/machine/machine_stm32f407.go
src/runtime/runtime_atsamd21.go
src/runtime/runtime_stm32f103xx.go
src/runtime/runtime_stm32f407.go
tools/gen-device-avr.py
tools/gen-device-svd.py

This PR adds a `HasBits()` method to all of the volatile registers, to allow for a simpler syntax for the very common bit comparison operations especially those performed in loops.
This was discussed in https://github.com/tinygo-org/tinygo/pull/358#discussion_r285389690

machine, runtime/all: Add HasBits() method to all registers

---

.circleci/config.yml

This should fix compatibility with the Go 1.12 stdlib:
https://github.com/tinygo-org/tinygo/issues/368

ci: install Go 1.12.5 on macOS

---

cgo/cgo.go
cgo/libclang.go
cgo/libclang_stubs.c
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

Bitfields are not supported by regular CGo, but because they are often used on embedded systems we really need them.
Unfortunately, there is no simple way to support them as Go (quite reasonably!) does not support them. Therefore, CGo will create getters and setters for bitfields avoiding complexity in the rest of the compiler.

cgo: add support for bitfields using generated getters and setters

---

cgo/cgo.go
cgo/libclang.go
testdata/cgo/main.go
testdata/cgo/main.h

This is necessary for most non-trivial CGo code (example: the nRF SoftDevice).

cgo: add support for anonymous structs

---

compiler/compiler.go
ir/ir.go
src/device/arm/arm.go
src/machine/buffer.go
src/machine/machine_atmega.go
src/machine/machine_attiny.go
src/machine/machine_avr.go
src/machine/usb.go
src/runtime/runtime_atsamd21.go
src/runtime/runtime_nrf.go
src/runtime/runtime_qemu.go
src/runtime/runtime_stm32f103xx.go
src/runtime/runtime_stm32f407.go
src/runtime/volatile/register.go
tools/gen-device-avr.py
tools/gen-device-svd.py

Split up in multiple commits to make it easier to review and find regressions, if any.
One bigger change is that I moved the `Register`* types to runtime/volatile. This makes it easier to share them. However, a 'register' type is now also used for ISR flags and regular volatile values (for example, in a ring buffer) so maybe it should be renamed?

Remove `//go:volatile` pragma

---

BUILDING.md

Some form of info here about needing `--recursive` would be useful, otherwise people can be caught out.

Add a note to use --recursive when cloning the TinyGo repo

---

compiler/channel.go
compiler/compiler.go
compiler/defer.go
compiler/func-lowering.go
compiler/func.go
compiler/goroutine-lowering.go
compiler/interface-lowering.go
compiler/interface.go
compiler/symbol.go
ir/ir.go

Trying to get rid of the `ir` package, that is not necessary anymore and has been holding back other refactors (in particular, #285).
There is more to come, but refactoring functions in the same way has far more side effects so needs some more fixes (like #399).

compiler: refactor globals and named types

---

Makefile

It is not necessary and does not exist in LLVM 9.

Makefile: drop the -lclangToolingRefactor library

---

compiler/channel.go
compiler/compiler.go
src/runtime/chan.go
testdata/channel.go
testdata/channel.txt

Non-blocking selects are much easier to implement, so let's do that first. It should get a bit more code to compile as well (but not necessarily to run well). It depends on #401 because there would be merge conflicts otherwise.
And yes, this is also part of #285 because the time package contains a select that used to be not compiled but will be with that refactor.

Implement non-blocking select statements

---

compiler/compiler.go
loader/loader.go
main.go
target.go

This commit fixes the case where TinyGo was built with `go build` and
LLVM sources were never downloaded into the TinyGo source directory.

all: try more locations to find Clang built-in headers

---

main.go

This PR should replace the use of `ExitStatus()` in the `tinygo test` command with an uglier syntax for handling test exit that apparently worked in go.11.

test: replace ExitStatus() with go1.11 compatible syntax

---

src/runtime/gc_marksweep.go

This is a rather critical error and I wonder why it hasn't been discovered earlier.

runtime: fix a heap corruption where some blocks were not marked as reachable

---

main.go

When running tinygo build/run/test, and the positional argument for the package is not specified, default it to "."
The go command for run doesn't default the package, but it seems like it could, and it is a nice feature, so I did it for tinygo run as well.

main: Default package name to current directory

---

.circleci/config.yml
Makefile

Now using a more simplified change than the original PR, to use the system compiler for both LLVM and the TinyGo binary. :smile:

Makefile: use official LLVM GitHub monorepo

---

main.go

Use a type switch instead of an if/else chain. This results in much more
readable code. There should be no functional change.

main: small refactor in error printing

---

src/machine/board_reelboard.go

adds PowerSupplyActive to enable supply voltages to nRF52840 and

---

compiler/compiler.go
compiler/defer.go
compiler/gc.go
compiler/optimizer.go
interp/frame.go
interp/scan.go
main.go
src/runtime/gc_conservative.go
src/runtime/gc_globals_conservative.go
src/runtime/gc_globals_precise.go
src/runtime/gc_leaking.go
src/runtime/gc_stack_portable.go
src/runtime/gc_stack_raw.go
targets/avr.json
targets/cortex-m.json

Improve the garbage collector to be portable to all platforms.
It currently implements a portable way of scanning globals, so that the compiler does not need to rely on special linker symbols to find globals (as provided in the Cortex-M targets). However, it does not yet implement a portable way of scanning the stack, which is especially important on WebAssembly as WebAssembly provides no way of directly accessing the stack. This means it is not safe to use this GC just yet (but it may happen to work for some limited use cases, no guarantees).

portable conservative garbage collector

---

compiler/compiler.go
compiler/goroutine-lowering.go
compiler/wordpack.go

Track some more allocations (in particular, during goroutine lowering) because not tracking them causes use-after-free errors.

Fix memory corruption in the portable garbage collector

---

.circleci/config.yml

This makes the LLVM source code cacheable again. The problem was likely introduced in #408.

ci: fix cache paths for LLVM source

---

tools/gen-device-svd.py

The first commit is a small refactor. I hope that we can move more and more towards such code (that is less procedural).
The second commit fixes some issues with a more recent cmsis-svd repository. Some of the newer stm32 files have a few issues. This commit makes the conversion a bit more forgiving.
These changes have been tested by comparing all older .go files before and after this commit, and there is no difference between them. That means it should not break backwards compatibility.

Add support for newer SVD files in cmsis-svd repository

---

compiler/compiler.go
compiler/gc.go
ir/ir.go
src/runtime/gc_conservative.go

This implements a few optimizations that together reduce the repulsion demo WebAssembly from 100.2kB to 96.7kB. It also allows the repulsion demo to run much longer when a bigger heap has been configured (that's not yet an option but the code can be manually modified).
@johanbrandhorst

Optimize stack pointer tracking

---

main.go
src/runtime/arch_wasm.go
targets/wasm.json

When the target supports it, allow the (initial) heap size to be
configured. This is useful for WebAssembly, for example.
This also changes the default heap size of WebAssembly from 64kB to 1MB.

all: make the heap size configurable

---

src/runtime/math.go

In particular, add support for a few math intrinsics for WebAssembly,
but add a few intrinsics to other systems as well at the same time. Some
may be missing still but will be easy to add if needed.
This increases the performance of one example by 50% to 100% depending
on the browser: the bottleneck was the inefficient sqrt implementation.
Note that the seemingly inefficient string comparisons are fully optimized away.

runtime: add support for math intrinsics where supported

---

linker-builtin.go
linker-external.go

In particular, while LLVM lld supports -L for linker scripts imported with the `INCLUDE` command, GNU ld does not seem to support this.
This is a prerequisite for supporting the HiFive1 board in the TinyGo Playground.

main: set the current working directory when calling an external linker

---

targets/arduino-nano33.json
targets/feather-m0.json
targets/itsybitsy-m0.json
targets/trinket-m0.json

Allow flash-time setting of device paths for several common boards.
bossac CLI tool doesn't properly resolve device paths for these (and probably others) on macOS
`tinygo flash -target arduino-nano33 -port=/dev/tty.usbmodem145101 ./main.go`

Device path at flash time for several boards

---

.circleci/config.yml

The build broke because the images got upgraded from stretch to buster.
Specify the stretch images (for now) so that it works again.
We can upgrade to buster for go1.12 at a later time.

ci: fix Go image on the Debian Stretch images

---

.circleci/config.yml
CHANGELOG.md
version.go

This release contains a small fix for some atsamd21-based boards to make them usable on macOS: it now allows to specify the serial port using the `-port` flag.

main: version 0.7.1

---

compiler/asserts.go
compiler/compiler.go
testdata/slice.go

This feature was introduced in Go 1.2 and is used by some standard library packages.
With this change, the crypto/md5 and image/draw packages start to work in the import report.

compiler: implement full slice expression

---

src/runtime/runtime_avr.go
src/runtime/runtime_cortexm.go
src/runtime/runtime_fe310.go

See the following bug: https://bugs.llvm.org/show_bug.cgi?id=42881
I think this is a bug in LLVM, but the code in question wasn't the best
code anyway. By fixing this, about 16 bytes of code are saved on ARM
chips (and much more on AVR).

runtime: work around a bug in LLVM for .bss zeroing

---

compiler/func.go
compiler/interface.go
compiler/reflect.go
src/reflect/sidetables.go
src/reflect/type.go
src/runtime/func.go
src/runtime/interface.go
testdata/interface.go
testdata/reflect.go
testdata/reflect.txt

Multiple commits to add more support for reflect:
1.  compiler: fix crash with linked lists in interfaces
Also, it prepares for some other reflect-related changes that should make it easier to add support for named types (etc.) in the future.
Together with #472, this should make the `"image/png"` package importable.
2. reflect: add support for named types
fixes #309

Improve interface and reflect support

---

Dockerfile

Debian stable-slim image now based on buster not stretch, so this PR updates the needed package repo used for LLVM, so that the Docker image for `dev` can build correctly.

docker: Debian stable-slim image now based on buster not stretch

---

CONTRIBUTORS

This PR adds a CONTRIBUTORS file to repo to clarify who are the famous "The TinyGo Authors".

governance: add CONTRIBUTORS file to repo

---

compiler/goroutine-lowering.go

This is a workaround for an existing issue, to see which function is to blame.
It should be fixed in a better way, but this provides at least a hint where to look to debug this issue.

compiler: make goroutine lowering panic message more helpful

---

compiler/compiler.go
compiler/goroutine-lowering.go
compiler/interface.go
src/runtime/scheduler.go

The first commit allows testdata/coroutines.go to be compiled for AVR. It fails during optimizing due what appears to be a LLVM error (see commit message for details).
While looking into this, I found some errors that have been fixed in the second commit.

Make testdata/coroutines.go AVR compatible

---

src/testing/benchmark.go
tests/tinygotest/main_test.go

This struct allows test files containing basic benchmarks to compile
and run, but will not run the benchmarks themselves.
For #491

testing: Add Benchmark B struct stub

---

compiler/interface.go
compiler/llvm.go
compiler/reflect.go
src/reflect/sidetables.go
src/reflect/type.go
src/reflect/value.go
testdata/reflect.go
testdata/reflect.txt

Linked lists are usually implemented as follows:
type linkedList struct {
next *linkedList
data int // whatever
}
This caused a stack overflow while writing out the reflect run-time type
information. This has now been fixed by splitting the allocation of a
named type number from setting the underlying type in the sidetable.
---
Oh man, this bug took so long to fix! I somehow just couldn't grasp the problem well enough, causing me to work on it for a whole day...
This should fix the remaining issue in #466 that causes the build to fail there. (That doesn't mean that PR is mergeable, but should get CI green at least).

Fix linked lists in reflection

---

compiler/compiler.go
testdata/slice.go

This was an oversight in the main commit for full slice expressions:
https://github.com/tinygo-org/tinygo/pull/472
This syntax is used by the regexp package, for example.

compiler: add support for full slice expression for slicing arrays

---

src/testing/benchmark.go
src/testing/testing.go
tests/tinygotest/main_test.go

Implements nearly all of the test logging methods for both T and B
structs. Majority of the code has been copied from:
golang.org/src/testing/testing.go
then updated to match the existing testing.go structure.
Code structure/function/method order mimics upstream.
Both FailNow() and SkipNow() cannot be completely implemented,
because they require an early exit from the goroutine. Instead,
they call Error() to report the limitation.
This incomplete implementation allows more detailed test logging and
increases compatiblity with upstream.

Add common test logging methods such as Errorf/Fatalf/Printf

---

compiler/compiler.go
compiler/goroutine-lowering.go
src/runtime/scheduler_tasks.go

A bug was introduced in the previous commit that led to miscompilations
in the time.Sleep function when the scheduler was disabled, because
time.Sleep (implemented in the runtime) tried to switch to the scheduler
stack.
This commit restores the binary size of most examples to what it was
before, but still reduces static RAM consumption (.bss) slightly. This
gives me some confidence that it does indeed fix the introduced bug.

compiler,runtime: fix new task-based scheduler

---

compiler/compiler.go
compiler/func-lowering.go
compiler/func.go
compiler/goroutine.go
testdata/coroutines.go
testdata/coroutines.txt

This commit allows starting a new goroutine directly from a func value,
not just when the static callee is known.
This is necessary to support the whole time package, not just the
commonly used subset that was compiled with the SimpleDCE pass enabled.
---
This is the first commit of #466, splitting it off because it is useful in general and makes the PR somewhat smaller.

compiler: add support for 'go' on func values

---

src/reflect/type.go
testdata/reflect.go
testdata/reflect.txt

This is necessary to support the context package, which is a dependency of a lot of packages.
---
Unfinished: it depends on array support to pass the tests.

reflect: implement t.Comparable()

---

tools/gen-device-avr.py
tools/gen-device-svd.py

This allows the tools to be used for Python 2 and Python 3, and makes it easier to support Windows.
I have quickly verified that there should be no observable difference when using Python 2: all files generated for nrf and for avr are identical.

tools: make tools python2 compatible

---

tools/gen-device-svd.py

Using 'is' for literals is incorrect, and only should be done for singletons.

Fix a Python SyntaxWarning.

---

src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine_atsamd21.go

Currently this code assumes that a atsamd21 board has a single SPI sercom:
https://github.com/tinygo-org/tinygo/blob/7d5542dda73e8dda066b604870eac279cd644a7e/src/machine/machine_atsamd21.go#L889
This is problematic for 2 reasons:
1) Some boards are designed with a second sercom configured for SPI such as Itsy Bitsy M0 (for SPI flash on sercom 5) and Arduino Nano 33 IOT (for SPI connection to ESP32 on sercom 2)
itsy bitsy: https://cdn-learn.adafruit.com/assets/assets/000/054/505/original/adafruit_products_schem.png?1527457190
nano IOT: https://content.arduino.cc/assets/NANO33IoTV2.0_sch.pdf
2) Even if boards don't have on-board peripherals attached as above, if the pins for unused sercoms are broken out on the board, users may wish to configure them for SPI
I'm not sure what that should …

Updated SPI pins so that they are configurable, enabling multiple SPI sercoms for ATSAMD21

---

src/runtime/scheduler.go

I solved #526 by simplifying some of the code for managing the timer queue.

fix sleep queue corruption bug

---

src/machine/machine_atsamd21.go

This PR corrects issue with invalid first reading coming from ADC, as discussed in https://github.com/arduino/ArduinoCore-samd/issues/446

machine/atsamd21: correct issue with invalid first ADC reading

---

src/machine/machine_atsamd21.go
src/machine/usb.go

This PR corrects order of params for USB CDC descriptor. It still works the same way, this just make it consistent. It also removes the interrupt handler for `usb_CDC_ENDPOINT_IN` as there is was no code that actually enables it.

machine/atsamd21: correct order of params for USB CDC descriptor

---

Dockerfile

This PR modifies the Dockerfile used for the `tinygo-dev` image to use the Go 1.12 base Docker image for compatibility.

docker: use Go 1.12 base Docker image for compatibility

---

compiler/compiler.go
ir/ir.go
src/examples/wasm/README.md

I need to compile a WebAssembly program that imports functions from a host that uses a module namespace other than the standard `env`.  I enhanced `go:export` to support this.  For example, in addition to the default export (`env` module)
```go
//go:export multiply
func multiply(x, y int) int {
return x * y;
}
```
You can set the module using `//go:export [module] <name>`
```go
//go:export math multiply
func multiply(x, y int) int {
return x * y;
}
```
Alternatively, you can use a separate comment `//go:module <name>` in conjunction with `go:export` or `go:linkname`.  I'm happy to make any tweaks to the argument format.
I tried to run `make test` but got clang linker errors.  I tested using `go install` and `wasm2wat` to print the imports of the compiled wasm.
This is a first step for …

WASM: Support for setting an imported function's module name

---

src/device/arm/arm.go
src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine_atsamd21.go

This PR is a draft for adding a software-based system reset to be able to flash new software on SAMD21 boards without pushing the reset button to start the bootloader.

machine/samd21: Implement reset processor 

---

main.go

This PR checks the current installed version of Go before running TinyGo to ensure that it is a supported version, before trying to compile anything. Should help prevent confusion for people with either old, or overly new versions of Go.

main: check the current installed version of Go before running TinyGo

---

Makefile
src/machine/board_itsybitsy-m4.go
src/machine/machine_atsamd51.go
src/machine/machine_atsamd51g19.go
src/runtime/runtime_atsamd51.go
src/runtime/runtime_atsamd51g19.go
targets/atsamd51.ld
targets/atsamd51g19a.json
targets/itsybitsy-m4.json

This PR adds support for atsamd51 processor using Adafruit ItsyBitsy M4 board.
Before it can be merged, both PR #542 as well as #543 must be merged first, as this PR requires this functionality..

machine/atsamd51: add support for atsamd51 processor/Adafruit ItsyBitsy-M4

---

compiler/calls.go
compiler/channel.go
compiler/compiler.go
compiler/defer.go
compiler/gc.go
compiler/interface.go
compiler/optimizer.go
compiler/symbol.go
compiler/wordpack.go
interp/frame.go
interp/utils.go
interp/values.go

It does the same thing but should be more complete, and it probably is faster as well (just one CGo call instead of several). I had totally missed that there was already a function in the go-llvm package that does this.
It would be nice to merge this before #511 so that the refactor can also follow the new format. These likely conflict, I'll update the other PR when one gets merged.

compiler: rename getZeroValue to llvm.ConstNull

---

.circleci/config.yml
Makefile
compiler/optimizer.go
go.mod
go.sum
transform/allocs.go
transform/allocs_test.go
transform/llvm.go
transform/maps.go
transform/maps_test.go
transform/testdata/allocs.ll
transform/testdata/allocs.out.ll
transform/testdata/maps.ll
transform/testdata/maps.out.ll
transform/transform.go
transform/transform_test.go
transform/util.go

Move transformation passes to a new package, and add unit tests.
This PR is just a first step. I hope to move most if not all passes to this new package, to make the compiler package simpler. This is part of the overall goal to refactor the compiler: #285.
The tests depend on a change in the go-llvm package so is not finished yet: https://reviews.llvm.org/D66379

Refactor transformation passes

---

src/machine/machine_stm32f103xx.go

The SPI frequency is broken since https://github.com/tinygo-org/tinygo/commit/b8c326d710a88877413e550b06100d9b79373dcd added I2C interface and changed the unrelated `PCLK2 = HCLK/4` initialization to `PCLK2 = HCLK/1` (I2C uses PCLK1).
This commit changes all baud rate prescalers to be `/4` compared to before - it is not possible to find an equivalent for 125 KHz SPI speed, it will be too fast (`f = 72 MHz / 256`).

machine/stm32f103xx: fix SPI frequency selection

---

src/machine/machine_stm32f103xx.go

I wanted to use a button and noticed that `Pin.Set()` is implemented for stm32f103xx but `Pin.Get()` not - maybe I'm missing something obvious but other `machine_*.go` include both so I figured it's the right way to add it.
I tested with a simple `for { led.Set(button.Get()); time.Sleep(time.Millisecond * 10) }` on my stm32f103xx board and it worked.

machine/stm32f103xx: Add machine.Pin.Get method

---

main.go

The above changes might indeed introduce inconsistencies in the IR, but
the code is small and doesn't change often so it's unnecessary to always
check for errors. It will be tested again later anyway.
The compile time impact was somewhere around 6%, so that's a nice
improvement.

main: stop running the LLVM verifier for trivial changes

---

src/runtime/runtime_cortexm.go

A call to memcpy is sometimes created by the compiler, for example when compiling with `-opt=s` or `opt=2`.

runtime: implement memcpy

---

src/machine/board_bluepill.go
src/machine/machine_stm32f103xx.go

Motivation: The bluepill uses USART1 as UART0 but other boards like the STM32 Nucleo boards (and disco as well) use USART2 for USB virtual COM port.
In the future I would like to contribue support for a STM32 Nucleo board which is why I want this refactoring.
To avoid duplication of code the same pattern as in `machine_atsamd21.go` and e.g. `board_arduino_nano33.go` is applied where only UART-specific variables and interrupt handling code (due to the export) is moved to `board_*.go`.
Please let me know what you think, maybe @aykevl or @deadprogram, as I don't own a bluepill so I cannot test for regressions - in theory everything should continue to work transparently.

machine/stm32f103xx: allow board specific UART usage

---

Makefile
README.md
src/machine/board_nucleof103rb.go
src/machine/board_stm32.go
targets/nucleo-f103rb.json
targets/stm32f103rb.ld

Product: https://www.st.com/en/evaluation-tools/nucleo-f103rb.html
Compared to the already supported stm32f103xx "bluepill" board this:
- features 128 KiB flash memory size ("RB" suffix) instead of 64 KiB, see `targets/stm32f103rb.ld`
- has onboard ST-LINK/V2-1 programmer and debugger requiring different OpenOCD configuration file
- uses USART2 connected to ST-LINK/V2-1 debugger as virtual COM port over USB for `putchar()`
- has a user-accessible button besides the reset button
I own a NUCLEO-F103RB board and would love to see it supported by tinygo. I already ran a couple of tests on it:
- it can be flashed and initialized successfully with 72 MHz `HCLK`
- `blinky1`, `echo` and `button` examples work
- I2C works
- manually configured GPIO interrupts work
Do I need to supply anything else …

machine/stm32f103xx/nucleo-f103rb: add support for Nucleo F103RB STM32F1-based board

---

target.go

This is similar to setting `FINAL_GOROOT` when building standard Go.
Falling back to one directory above executable path doesn't work since the executable would be in `/usr/bin/tinygo` (`TINYGOROOT=/usr`) or `/bin/tinygo` (`TINYGOROOT=/`). When building a package, the build location has no correlation of where the files will end up once built. So falling back to "original directory from where it was built" does not work, either.

Add a way to bake-in final TINYGOROOT.

---

src/machine/machine_nrf.go
src/machine/spi.go

The SPI peripheral in the nrf chips support double buffering, which makes it possible to keep sending continuously. This change introduces double buffering on the nrf chips, which should improve SPI performance.
Tested on the pca10040 (nrf52832).
I'm not very happy with the code duplication but I didn't see a clean way to do it otherwise (suggestions welcome).
@conejoninja you may be interested in this: it should improve the performance of the hub75 driver.

nrf: improve SPI write-only speed, by making use of double buffering

---

src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine_atsamd21.go

This PR allows use of `PinMode` for SPI SERCOM peripherals to allow for more configuration options on boards like Arduino Nano33-IoT that have many predefined pin mappings.

machine/samd21: use PinMode for SPI SERCOM peripherals

---

src/runtime/runtime_atsamd21.go

This PR sets the minimum sleep to 214us due to minimum delay in register synchronization.
It corrects the remaining issues reported in #526

runtime/samd21: set minimum sleep to 214us

---

target.go
target_test.go

This PR corrects #506 by ensuring that any passed in target, if it does not point to a .json file, is a full LLVM triple.

compiler: ensure that any passed in target is valid

---

ir/ir.go
testdata/alias.go
testdata/alias.txt

During SSA construction, we used to run into issues where we would unintentionally create two IR function wrappers for the same function, which then resulted in one getting discarded during SimpleDCE and one not getting discarded. However, in the process of discarding one, we removed the other from the lookup table and therefore got null when attempting to look up the function.
This PR also adds a regression test, which also tests other aspects of type aliases.

Fix bug in IR regarding type aliases

---

Makefile
main.go
objcopy.go

This PR allow TinyGo to directly output GBA files that are ready for flashing by performing internal objcopy.
For example:
```
tinygo build -o ~/main.gba -target gameboy-advance examples/gba-display
```

machine/gameboy-advance: allow TinyGo to directly output GBA files

---

.gitignore

It was ignored before when the directory was still just called llvm, but
now it isn't anymore. Fix that.

gitignore: ignore llvm-project directory

---

Makefile

This commit makes 2 changes to the makefile:
1. You can use alternate go versions by running `make GO=go1.13` or similar
2. For building LLVM, ccache will be used if it is available on the current system

Update Makefile to allow selecting Go version and using ccache

---

Makefile
compiler/optimizer.go
transform/stringtobytes.go
transform/stringtobytes_test.go
transform/testdata/stringtobytes.ll
transform/testdata/stringtobytes.out.ll
transform/util.go

Unfortunately, while doing this I found that it doesn't actually apply in any real-world programs (tested with `make smoketest`), apparently because nil pointer checking messes with the functionattrs pass. I hope to fix that after moving to LLVM 9, which has an optimization that makes nil pointer checking easier to implement.

refactor OptimizeStringToBytes

---

src/reflect/type.go
src/reflect/value.go
src/runtime/interface.go

So before we were running into issues related to GEP operations through bitcasts. This should hopefully resolve this. I completely removed interfaceHeader, replacing it with a pair of functions inside `runtime` called `compose` and `decompose`. The `compose` and `decompose` functions are set to be always inlined in order to minimize overhead.
More testing may be necessary to ensure that this really works in a decent manner.

Remove the troublesome interfaceHeader from reflect

---

Makefile

This makes it much easier to check whether a binary changed at all, to avoid having to test it on real hardware.

Makefile: add md5sum to smoketest

---

.circleci/config.yml
Makefile
compiler/compiler.go
interp/frame.go
interp/interp.go
interp/interp_test.go
interp/scan.go
interp/testdata/basic.ll
interp/testdata/basic.out.ll
interp/testdata/slice-copy.ll
interp/testdata/slice-copy.out.ll
interp/values.go
main.go
testdata/init.go
testdata/init.txt

Two changes that depend on each other. I can split out the PR if that makes it easier to review.
* Add tests. Start out with a basic test to see whether interp roughly works.
* implement `runtime.sliceCopy` in the interp package. That function uses lots of pointer casting so it's hard to interpret it directly, therefore I implemented it directly in interp.
This change gets 3 packages to compile: encoding/base32, encoding/base64, and encoding/pem. With that, compiling encoding/json is one step closer.
Fixes #437.

interp: add tests and implement runtime.sliceCopy

---

src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/usb.go

This PR remove use of binary package to avoid reflection and reduce binary size for the SAMD21 and SAMD51 processors, as well as more generally for use of the USB CDC interface.

machine/samd21,samd51: remove use of binary package to avoid reflection for USBCDC

---

Makefile

`python` is Python 2, but I only have `python3` installed. There won't be `python`->`python3` until changes in PEP 394 are finally widespread, but even then I'd rather use the explicit one.

Allow overridding Python used for generators.

---

compiler/asserts.go
src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine.go
src/machine/machine_atsamd21.go
testdata/slice.go

Pin mode and pad numbers are automatically calculated from the pin numbers, returning an error if no pinout could be found.
Not yet properly tested. However, while doing some initial testing, I found that there was an inconsistency in the Nano 33 IoT pinout for SPI0: the MISO pin is `A6` or `PA09` which has SERCOM0/PAD1 while the `DIpad` was set to `sercomRXPad0` - thus SERCOM0/PAD0 (pin PA08). I don't know which of the two it is supposed to be and whether I didn't miss anything but I'm surprised this worked. @deadprogram can you take a look?
Also, are there espat examples for the Nano 33 IoT (or other SPI tests) that should work with little or no modification?
This is just the first step, my goal is to convert UART and I2C in the same way. And also see whether this is possible on the …

machine/atsamd21: refactor SPI pin handling to only look at pin numbers

---

src/runtime/runtime_avr.go

An optimization introduced in
https://github.com/tinygo-org/tinygo/commit/a04db67ea9d882eed9164321bcb503f76a65d2f1
seems to have broken arduino uno compiled hex. Setting optimzation
flags to 1, 2, or s builds proper hex binaries though.
These patches have been the result of troubleshooting over slack:
> @aykevl 
> that preinit also doesn't look right. Can you try this variant, with 8-bit stores instead of 32-bit stores?
> There might be some alignment issue: the _ebss might not be aligned resulting in ptr != unsafe.Pointer(&_ebss) never being true.
Co-authored-by: Ayke van Laethem <aykevanlaethem@gmail.com>
Co-authored-by: Jaden Weiss <jadr2ddude@gmail.com>

arduino: fix avr hex not working when flashed

---

src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine.go
src/machine/machine_atsamd21.go

Also, pick up pin mode from the pins itself instead of statically configuring it. As an added bonus, this reduces the chances of getting it wrong.

machine/samd21: refactor I2C pin handling to use pins in config struct

---

src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_express.go
src/machine/board_feather-m0.go
src/machine/board_itsybitsy-m0.go
src/machine/board_trinket.go
src/machine/machine_atsamd21.go

This allows all possible UART pin configurations to be used and avoids some tricky configuration.
Will rebase on top of dev once #597 lands.

machine/samd21: switch UART to use new pin configuration

---

src/runtime/string.go

This PR adds an implementation of bytealg.CountString to complete #424 based on the information located by @1l0

runtime/all: add implementation of bytealg.CountString to complete #424

---

src/machine/board_hifive1b.go
src/machine/machine_fe310.go
src/runtime/runtime_fe310.go

This PR adds support for the HiFive1 GPIO Get() as well as preparing for several other upcoming additions.
It requires a newer version of the cmsis-svd with the e510x SVD file.
This PR needs #601 be merged fist, and then I will update the PR to remove that commit.

machine/hifive1: complete support for GPIO Get() interface

---

src/machine/machine_nrf.go

Comparing slices against nil currently causes the slice to escape, due to a limitation in LLVM 8. This leads to lots of unnecessary heap allocations. With LLVM 9 and some modifications to TinyGo, this should be fixed. However, this commit is an easy win right now.
Returning an error when both slices are nil is not necessary, when the check is left out it should just do nothing.
For updating an SPI screen using the st7735 driver, this results in a ~7% performance win.

machine/nrf: do not compare slices against nil

---

go.mod
go.sum
main.go
target.go
targets/arduino-nano33.json

This PR adds ability to perform 1200baud port reset for MCUs that can detect this in order to go into bootloader mode for flashing without pressing any buttons. Also add support for this to the Arduino Nano33 IoT board target.
It provides a solution for #614

flash: add ability to perform 1200baud port reset for MCUs bootloader reset

---

main.go
target.go
targets/circuitplay-express.json
targets/feather-m0.json
targets/hifive1b.json
targets/itsybitsy-m0.json
targets/itsybitsy-m4.json
targets/microbit.json
targets/trinket-m0.json

This PR adds the ability to use the `tinygo flash` command on boards with the UF2 bootloader such as all the boards used by Adafruit. It requires that PR #616 be merged first.
You then then just run a command like this to flash an Adafruit ItsyBitsy M4:
```
tinygo flash -target itsybitsy-m4 examples/blinky1
```

flash: allow flash operation on boards with UF2 and Daplink bootloaders

---

src/machine/spi.go

This PR changes to not compare slices against nil, same as #612 but for all platforms that use shared SPI implementation for `Tx()`

machine/spi: do not compare slices against nil, same as #612

---

compiler/compiler.go
testdata/structs.go
testdata/structs.txt

Previously, the cycle was broken by inserting an `unsafe.Pointer` type in some places. This is of course incorrect, and makes debugging harder. However, LLVM provides a way to make temporary nodes that are later replaced, exactly for this purpose.
This commit uses those temporary metadata nodes to allow such recursive types.
Fixes #586.

compiler: support recursive types

---

main.go
target.go
targets/arduino-nano33.json
targets/arduino.json
targets/bluepill.json
targets/circuitplay-express.json
targets/digispark.json
targets/feather-m0.json
targets/hifive1b.json
targets/itsybitsy-m0.json
targets/itsybitsy-m4.json
targets/microbit.json
targets/nrf51.json
targets/nrf52.json
targets/nrf52840-mdk.json
targets/nrf52840.json
targets/nucleo-f103rb.json
targets/pca10031.json
targets/pca10040.json
targets/pca10056.json
targets/reelboard.json
targets/stm32f4disco.json
targets/trinket-m0.json

Instead of specifying explicit commands, most of these commands have been replaced by more specific properties.
This is work that will be necessary for an eventual `-programmer` flag to the compiler, with which it is possible to select which programmer to use to flash or debug a chip. That's not very useful for boards that already include a programmer or bootloader for that purpose, but is very useful for novel boards or single-purpose boards that are not already included in TinyGo. It also avoids a lot of boilerplate and may allow custom .json descriptors in programs with only known-safe properties.
---
I have tested all the boards I could get my hands on:
* Arduino Uno
* Digispark
* pca10040
* pca10056: couldn't get the debugger to work and I suspect that configuration was wrong anyway, …

targets: refactor flash/gdb target configuration

---

buildcache.go
builtins.go
goenv/goenv.go
linker-builtin.go
linker-external.go
main.go
target.go

This is required for compatibility with Visual Studio Code. It doesn't complete support, but it is one step along the way.

Implement the go env subcommand

---

src/sync/pool.go

With `sync.Pool`, `New` is allowed to be nil so that applications can implement their own behavior. This patch makes tinygo's `sync.Pool` work properly when a `New` func is not specified.

properly handle nil New func in sync.Pool

---

src/runtime/scheduler.go

This was a micro-optimization I worked on when messing around with #513. I later put it in #606.
Basically:
1. When running scheduler-heavy code (in the original case a goroutine/channel benchmark), the scheduler gets bottlenecked by expensive calls to check the time on the system. This patch allows us to skip the check and get a [massive improvement in performance](https://twitter.com/CompuJad/status/1168357191230853120?s=20).
2. When a piece of code does not care about timing, `sleepQueue != nil` gets constant-folded to false and all of the timing code gets optimized away.

Skip calling ticks when the sleep queue is empty

---

azure-pipelines.yml

Note: waiting for CI to check that the PR is still being built...

ci: avoid rebuilding LLVM on Azure (Windows)

---

src/device/arm/arm.go
src/examples/systick/README.md
src/examples/systick/systick.go

Add SYST registers and bit definitions to device/arm.
Add a setup function.
Add an example that uses it to blink an LED.
See also issue #651.

device/arm: add system timer registers

---

compiler/interface-lowering.go
testdata/reflect.go
testdata/reflect.txt

When using reflect, arbitrary types can be synthesized. This invalidates
a few assumptions in the interface-lowering pass, that think they can
see all types that are in use in a program and optimize accordingly.
The file size impact depends on the specific program. Sometimes it's
nonexistent, sometimes it's rather hefty (up to 30% bigger). Especially
the samd21 targets seem to be affected, with a 2000-6000 bytes increase
in code size. A moderately large case (the stdlib test) increases by
4%/6%/15% depending on the target.
I hope that this increase could be mitigated, but I don't see an obvious
way to do that.

compiler: fix interface lowering miscompilation with reflect

---

src/runtime/runtime_atsamd51.go

This PR corrects the initialization for RTC by not overwriting all other other bits in the `OSCULP32K` register.

runtime/samd51: correct initialization for RTC

---

compiler/check.go
compiler/optimizer.go

use error returns to generate detailed error messages in the IR checker

---

Makefile

This makes sure future changes will at least keep the example code compiling. See #654.

Makefile: add systick example to smoke tests

---

src/machine/machine_atsamd51g19.go

I caught this during code review.  Shift is higher precedence than subtraction, so it does the shift and then subtracts 32 from the shift result.
The PinOutput case does it properly, these other cases are wrong.
Here's a simple Go Playground program to show the problem: https://play.golang.org/p/JkdtsZRNvuw

machine/atsamd51: pin function selection bugs

---

src/machine/machine_atmega.go

This pull request is for Arduino Uno. This patch enables the A0-A5 pins to be used as GPIO 14-19.

machine/atmega: add PORT C GPIO support

---

Makefile
src/machine/board_pinetime-devkit0.go
targets/pinetime-devkit0.json

This smartwatch doesn't have an on-board debugger, so I picked the one I was using while getting this smartwatch to run Go programs (the J-Link EDU Mini).

nrf: add support for the PineTime64 devkit

---

Makefile

One board (pca10040) was already tested. To make sure stuff doesn't break in the future, test all the other boards too.

Makefile: add simulated boards to smoke tests

---

main.go

Most programmers support the "reset halt" command, which resets the
target but keeps it halted at the first instruction. This is a much more
natural way of working with GDB, and allows setting breakpoints before
the program is started.
This commit switches to `reset halt` by default and also stops running
the program directly when debugging natively on the host.
You will now have to run `run` or `continue` manually after dropping in the GDB shell.

main: halt GDB on start

---

src/machine/board_fe310.go
src/machine/board_hifive1b.go
src/machine/machine_fe310.go
src/machine/spi.go

This PR adds support for SPI1 to the SiFive HiFive1b development board. Tested with APA102 LED strip.

machine/hifive1b: add support for SPI1

---

src/machine/board_fe310.go
src/machine/board_hifive1b_baremetal.go

CI started to fail because a file with just the hifive1b build tag also imported the device/sifive package. That doesn't work for wasm, necessary for play.tinygo.org.

machine/hifive1b: fix compiling in simulation (wasm)

---

main.go
target.go

This fixes a crash crash with the -ocd-output flag. It wasn't used elsewhere anyway.

main: remove ocd-daemon property

---

src/machine/board_itsybitsy-m4.go
src/machine/machine_atsamd51.go

This PR allows setting pinmode for each of the SPI pins individually on the SAMD51 processor, since some SERCOM settings require both the Sercom and SercomAlt muxes be set at the same time. This allows the default SPI0 to be used on the ItsyBitsy-M4 for bi-directional SPI devices that both read and write data. The previous code only worked for write-only devices like the APA102 LEDs.
I looked at the mux functions that were used for the SAMD21, but the SAMD51 has more SERCOMs and more possible pad settings, so the code would require some adaptation to be used. That will have to be for a future PR.

machine/samd51: allow setting pinmode for each of the SPI pins

---

Makefile

This PR corrects the source for SiFive SVD files as used in the device wrapper generator.

gen-device: correct source for SiFive SVD files

---

src/machine/board_itsybitsy-m4.go
src/machine/machine_atsamd51.go

This PR corrects the channel init for ADC on the SAMD51 processor. It also corrects the pin map for pin A1 on the ItsyBitsy-M4.

machine/samd51: correct channel init and pin map for ADC

---

compiler/compiler.go
compiler/func-lowering.go
compiler/goroutine.go
testdata/coroutines.go
testdata/coroutines.txt

This PR fixes #508
Previously, spawning a goroutine with a closure whose function is statically known would result in a call that did not pass in the closure context. This resulted in undefined behavior. After copying in the appropriate context extraction code, the function-lowering pass attempted to transform the `makeGoroutine` operation, which caused the code to compile but have an LLVM assertion failure. The relevant code in the function-lowering pass has been modified to ignore `makeGoroutine` calls.

Fix miscompile of static calls to closures

---

Makefile
README.md
src/machine/board_x9pro.go
targets/x9pro.json

This is a Chinese smart watch sold on AliExpress etc. It is based on a nrf52832. More information:
https://github.com/curtpw/nRF5x-device-reverse-engineering/tree/master/X9-nrf52832-activity-tracker
The HR LED and the display work.
---
I'm wondering, what's the threshold for adding boards? This is just a generic smartwatch that may disappear in a few years. It's basically all reverse engineerd. I happen to have one lying around from the time before the PineTime (that would definitely be my preference now!).

machine: add support for the X9 Pro smartwatch

---

.circleci/config.yml
Makefile
cgo/cgo.go
cgo/cgo_test.go
cgo/testdata/basic.go
cgo/testdata/basic.out.go
cgo/testdata/types.go
cgo/testdata/types.out.go

Add tests to CGo processing. They should not only be useful for testing, but also for documentation: you can easily see what CGo generates.
The formatting is somewhat messy but that is (I think) because CGo doesn't output very precise location information. This might be improved in the future but is not very important (it's more of an implementation detail).

cgo: add tests

---

cgo/libclang_config.go
commands.go
go.mod
go.sum

Fixing compile errors when LLVM is only installed to `/usr/local/opt/llvm@8` and not `/usr/local/opt/llvm`.
Note: must be merged together with https://github.com/tinygo-org/go-llvm/pull/10

macos: use llvm@8 instead of just llvm in paths

---

compiler/channel.go
src/runtime/chan.go
testdata/channel.go
testdata/channel.txt

This pull request adds support for blocking select operations, and fixes some bugs in the compiler I came across in the process.
At the moment, this may add additional allocations to channel operations. I have some ideas for how to mitigate this, but I thought it would be appropriate to at least publish what I have so far.

Add blocking select

---

go.mod
go.sum

This PR updates the modules to use latest version of the `go-llvm` package. It should correct the Azure CI build problems.

go-llvm: update modules to use latest version

---

compileopts/config.go
compileopts/target.go
main.go
targets/arduino.json
targets/atsamd21e18a.json
targets/atsamd21g18a.json
targets/atsamd51g19a.json
targets/bluepill.json
targets/digispark.json
targets/gameboy-advance.json
targets/hifive1b.json
targets/nrf51.json
targets/nrf52.json
targets/nrf52840.json
targets/nucleo-f103rb.json
targets/qemu.json
targets/stm32f4disco.json

Setting the linker script as one property (instead of as part of the generic ldflags property) allows it to be overriden.
This is important for the SoftDevice on Nordic chips, because the SoftDevice takes up a fixed part of the flash/RAM and the application must be flashed at a different position. With this linkerscript option, it is possible to create (for example) a pca10040-s132v6 that overrides the default linker script.
Depends on #677.

Make linker script an independent property

---

main_test.go

This PR restructures the tests, and assigns names to tests which explicitly state what platform they are testing. Most of this is ripped out of #641.

Make compiler test names clearer

---

cgo/cgo.go
cgo/const.go
cgo/const_test.go
cgo/libclang.go

This PR factors out constant handling (mapping C `#define` to Go constant expressions) and improves the parsing of such constants significantly. For example, for the following C code:
```c
#define CONST_INT 5)
```
You may get the following compile error:
```c
testdata/cgo/main.h:19:20: unexpected token )
```
Previously this error would be handled by simply not defining `CONST_INT`.
As a followup, I'd like to implement simple expressions like `SOME_CONST + 5`. This is required for SoftDevice support.

cgo: improve handling of constants

---

Makefile
README.md
src/machine/board_feather-m4.go
src/machine/machine_atsamd51j19.go
src/runtime/runtime_atsamd51j19.go
targets/atsamd51j19a.json
targets/feather-m4.json

Adding support for Adafruit Feather M4 Express: https://www.adafruit.com/product/3857
Schematic is here: https://cdn-learn.adafruit.com/assets/assets/000/057/242/original/arduino_compatibles_schem.png?1531010817
Currently WIP; the board/machine files are mostly copied from Itsy Bitsy M4 (with updated pin mappings of course) but this is the 64-pin version of the chip. It is mostly working except for SPI0.   I will do troubleshooting on what might be wrong with it a little later unless someone else notices what the problem might be before that.

Adding Board: Feather M4 Express

---

cgo/cgo.go
cgo/libclang.go
cgo/testdata/types.go
cgo/testdata/types.out.go

This PR renames reserved field names like `type` to `_type`, and in turn renames those fields as well (recursively). This avoids name clashes when a C struct contains a field named `type`, which is a reserved keyword in Go.
For some details, see: https://golang.org/cmd/cgo/#hdr-Go_references_to_C
This makes it possible to use the following struct in CGo:
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.s132.api.v6.1.1%2Fstructble__gap__adv__properties__t.html
---
Sidenote: this PR really shows the value of the testing I set up in #683.

cgo: rename reserved field names like `type`

---

main.go

It lists some information about the device that is useful for tools, in a way that can be parsed easily.
This PR is necessary for https://github.com/tinygo-org/tinygo-site/pull/47 to work.

main: add 'target' subcommand

---

cgo/libclang.go
cgo/testdata/types.go
cgo/testdata/types.out.go

Not all enums may be used as a type anywhere, which was previously the only way to include an enum in the AST. This commit makes sure all enums are included.
One example where this is needed is the following enum:
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.s132.api.v6.1.1%2Fgroup___b_l_e___g_a_p___e_n_u_m_e_r_a_t_i_o_n_s.html&cp=3_5_2_2_2_1_1_1&anchor=gada486dd3c0cce897b23a887bed284fef

cgo: include all enums in the CGo Go AST

---

cgo/cgo.go
cgo/libclang.go
cgo/testdata/types.go
cgo/testdata/types.out.go
compiler/compiler.go
compiler/interface.go
compiler/sizes.go
testdata/cgo/main.go

Instead of putting the magic in the AST, generate regular accessor methods. This avoids a number of special cases in the compiler, and avoids missing any of them which could cause compiler bugs.
The resulting union accesses are somewhat clunkier to use, but the compiler implementation has far less coupling between the CGo implementation and the IR generator.
---
`unionfield` looks a little bit ugly to me, if you have any better suggestions for a name please let me know!

cgo: refactor union support

---

cgo/cgo_test.go

When this flag is set, the `testdata/*.out.go` files will be updated when they have changed. This is very convenient for updating these files after the expected output changes.
Of course, the updated output must still be checked for validity.

cgo: add -update flag to tests

---

src/runtime/interface.go
testdata/interface.go

This was an oversight in https://github.com/tinygo-org/tinygo/pull/686. With this PR, it's possible to compare interface values that contain values/fields of type `uintptr`.
This makes `time.Now().Format()` work on baremetal systems (although it seems to fall back to UTC).

runtime: implement comparing uintptr values in interfaces

---

src/runtime/runtime.go

This function adjusts the time returned by `time.Now()` and similar functions. This is necessary on bare metal systems, where there would not be a way to adjust the time otherwise.

runtime: add AdjustTimeOffset to update current time

---

src/runtime/runtime_unix.go
src/runtime/runtime_unix32.go
src/runtime/runtime_unix64.go

The problem currently with #680 failing to pass tests appears to be that `ticks()` is returning corrupted time values. This PR fixes that by correcting some definitions for timing functions.

Fix ticks on 32-bit ARM on Linux

---

src/runtime/runtime_unix.go
src/runtime/runtime_unix32.go
src/runtime/runtime_unix64.go

There is no need for separate datatypes for 32-bit and 64-bit *nix systems, because the int type already provides this.
See https://github.com/tinygo-org/tinygo/pull/710

runtime/unix: simplify time functions

---

targets/arm.ld
targets/avr.ld
targets/gameboy-advance.ld
targets/riscv.ld

This prevents it from being of type PROGBITS in lld 9, it should always be NOBITS. This should fix the following error in lld 9:
ROM segments are non-contiguous
Note: I haven't yet tested this.
fixes #594

targets: explicitly mark the stack as NOLOAD

---

compileopts/config.go
compileopts/options.go
compileopts/target.go
main.go

This flag is overloaded. It can be used in two ways:
* Choosing the flash method to use (openocd, msd, command).
* Choosing the OpenOCD programmer name.
For example, you can use one of these to use OpenOCD instead of the mass-storage device programmer:
tinygo flash -target=microbit -programmer=openocd
tinygo flash -target=microbit -programmer=cmsis-dap
A future PR will fix PineTime support so that it can be programmed either with the J-Link (`-programmer=jlink`) or the ST-Link v2 (`-programmer=stlink`).
This PR can also be used to choose how the pca10040 should be programmed (with the default staying `-programmer=openocd`):
tinygo flash -target=pca10040 -programmer=command
tinygo flash -target=pca10040 -programmer=openocd

main: add -programmer flag

---

builder/ar.go
builder/builtins.go

This should fix an issue with LLVM 9 (specifically, ld.lld-9).
See: https://github.com/tinygo-org/tinygo/issues/595

builder: write a symbol table when writing out the compiler-rt lib

---

.gitmodules
Makefile
builder/builtins.go

We don't need the separate submodule: compiler-rt is already included in the llvm-project repository.
This should hopefully make CI slightly faster too. Also, it will make sure compiler-rt is automatically upgraded on each LLVM version upgrade.

all: use compiler-rt from the llvm-project directory

---

transform/allocs.go
transform/testdata/allocs.ll
transform/testdata/allocs.out.ll
transform/transform_test.go

Previously, we only zeroed stack allocations once in the entry block. However, when the original allocation is in a loop, it is necessary to zero the allocation on every iteration. This PR moves the allocation zeroing into the location where the `runtime.alloc` call used to be.

fix incorrect starting value for optimized allocations in a loop

---

compiler/goroutine-lowering.go

The `runtime.getFakeCoroutine` mechanism was originally added just so we had something to pass in as a parent handle for async tail calls. This PR optimizes it away when a parent handle is not necessary. At the moment, this is capable of optimizing it out of all `go` calls in `testdata/channel.go`.

Eliminate extraneous `runtime.getFakeCoroutine` calls

---

targets/nrf52-s132v6.json
targets/pca10040-s132v6.json

In my excitement to get the SoftDevice PR ready, I made two mistakes. They're fixed in this commit.
* Add the `s132v6` build tag.
* Remove the (old) `ldscript` property.
This fixes the following issue: https://github.com/aykevl/go-bluetooth/issues/1

nrf: fix nrf52-s132v6 config

---

compiler/gc.go
testdata/zeroalloc.go

Fixes the bug shown in https://github.com/tinygo-org/tinygo/issues/728#issuecomment-554684216, where a piece of code only calls `runtime.alloc` once and does a zero-size allocation.

add code to handle programs which use heap allocations but never hit the GC

---

interp/testdata/basic.ll
interp/testdata/basic.out.ll
interp/utils.go
interp/values.go

This bug was triggered by the following code:
package main
func foo() byte
var array = [1]byte{foo()}
func main() {
}

interp: fix inserting non-const values in a const aggregate

---

src/machine/board_arduino_nano33.go

This PR adds a SPI interface called SPI1 on SERCOM2 for the connection to the integrated ESP chip.  Additionally it adds aliases NINA_TX, NINA_RX, and NINA_SPI to make use of this connection more portable across boards.

Add SPI1 connected to NINA-W102 chip on Arduino Nano 33 IOT

---

src/machine/machine_atsamd21.go

I found these during code review, they look like bugs to me.  Unfortunately, I don't have atsamd21 hardware to test against, so please review carefully.
1. The I2S_SERCTRL_DATASIZE_* constants are 0-based, but DATASIZE is not at offset 0 within the SERCTRL register.  It should be shifted by 8, otherwise it will clobber the SERMODE and TXDEFAULT fields.
2. The Philips I2S spec is MSB-first.  The BITREV flag, when set, causes LSB-first operation.  I think the flag should be should be set in I2SStandardLSB mode, and clear in I2SStandardMSB and I2SStandardPhilips modes.
I think this PR will cause the `src/examples/i2s/i2s.go` example to print samples in the opposite order.  Were the samples printed correctly before?

runtime/atsamd21: i2s initialization fixes

---

src/machine/board_feather-m4.go
src/machine/board_itsybitsy-m4.go
src/machine/board_metro-m4-airlift.go
src/machine/machine_atsamd51.go

My initial implementation for UART2 on this Metro M4 Airlift Lite was simply incorrect.  This PR adds handlers to atsamd51.go so that this actually works.

Fixes for UART2 on Metro M4 Airlift Lite

---

src/runtime/scheduler_cortexm.S
src/runtime/scheduler_tasks.go

The Cortex-M architecture contains two stack pointers, designed to be used by RTOSes: MSP and PSP (where MSP is the default at reset). In fact, the ARM documentation recommends using the PSP for tasks in a RTOS.
This commit switches to using the PSP for goroutine stacks. Aside from being the recommended operation, this has the big advantage that the NVIC automatically switches to the MSP when handling interrupts. This avoids having to make every goroutine stack big enough that interrupts
can be handled on it.
Additionally, I've optimized the assembly code to save/restore registers (made possible by this change). For Cortex-M3 and up, saving all registers is just a single push instruction and restoring+branching is a single pop instruction. This results in a small code size improvement and …

runtime: use MSP/PSP registers for scheduling on Cortex-M

---

cgo/cgo.go
cgo/cgo_test.go
cgo/libclang.go
cgo/security.go
cgo/security_test.go
cgo/testdata/errors.go
cgo/testdata/errors.out.go
cgo/testdata/flags.go
cgo/testdata/flags.out.go
go.mod
go.sum

This implementation is still very limited but provides a base to build upon. Limitations:
* `CGO_CFLAGS` etc is not taken into account.
* These `CFLAGS` are not used in C files compiled with the package.
* Other flags (`CPPFLAGS`, `LDFAGS`, ...) are not yet implemented.

cgo: implement #cgo CFLAGS

---

.gitmodules
Makefile
builder/builtins.go

This reverts commit acdaaa17d8232989d310292a512e70fccdb288a5.
See https://github.com/tinygo-org/tinygo/issues/734 for details.

Revert "all: use compiler-rt from the llvm-project directory"

---

Makefile
azure-pipelines.yml

The default Go version is 1.12. Because Go 1.13 introduced language changes (improved numeric constants), TinyGo compiled with Go 1.12 cannot handle Go 1.13 code such as the Go 1.13 standard library.

ci: build with Go 1.13 on Windows

---

go.mod
go.sum
interp/errors.go
interp/frame.go
interp/interp.go
main.go

This commit improves error reporting in several ways:
* Location information is read from the intruction that causes the
error, as far as that's available.
* The package that is being interpreted is included in the error
message. This may be the most useful part of the improvements.
* The hashmap update intrinsics now doesn't panic, instead it logs a
clear error (with location information, as in the first bullet
point).
This is possible thanks to improvements in LLVM 9. This means that after
this change, TinyGo will depend on LLVM 9.
Example of the hashmap error improvement, before:
panic: interface conversion: interp.Value is *interp.LocalValue, not *interp.MapValue
After:
```
../../../../../usr/local/go/src/go/token/token.go:282:17: could not update map with string key
```
(Reading the …

interp: improve error reporting

---

interp/frame.go
interp/interp_test.go
interp/testdata/consteval.ll
interp/testdata/consteval.out.ll
interp/utils.go

This PR should fix the following error when trying to compile the tinygo branch of vugu:
```
src/sync/pool.go: interp: branch on a non-const-propagated constant expression
```
(The improved error message comes from #748).

interp: fix "interp: branch on a non-const-propagated constant expression"

---

interp/errors.go
interp/frame.go
interp/interp.go
interp/scan.go
interp/scan_test.go

This PR replaces most panics in interp/frame.go and interp/scan.go with real error messages. The remaining ones are panics that should not happen when working with valid IR. It builds upon #748 to improve error handling in the interp package.
There are a number of panics left in interp/value.go, but replacing them will require some more restructuring so I will do that at a later time.

interp: replace many panics with error messages

---

CODE-OF-CONDUCT.md

This PR adds an official code of conduct for the project using 'Contributor Covenant'.

docs: add official code of conduct using 'Contributor Covenant'

---

tools/gen-device-svd.py

This makes the generation script slightly simpler.
I checked whether any of the smoketest outputs changed with this, with the smoke tests of the main tinygo repository and the drivers repository. I could find only one difference: examples/apa102 in the drivers repository. However, when looking at the IR before and after, the difference was in some reflection data (which can indeed change when field names change). Therefore, I think that's an unrelated change (although it may be a good idea to test that example anyway).

tools: avoid _paddingX in generated struct fields

---

targets/riscv.ld

The .sdata and .sbss sections are created by the compiler, but were not
present in the linker script. That means that the compiler put them
after all other data/bss section, which happens to be where the heap
also resides.
This commit adds the .sdata and .sbss sections to the linker script,
which gets the blinky examples to work again on RISC-V.

riscv: fix heap corruption

---

.circleci/config.yml
Makefile
azure-pipelines.yml
targets/riscv.json
targets/riscv.ld

Now that we use LLVM 9, RISC-V support in LLVM has far fewer bugs and we can avoid the GNU toolchain.
* replace GNU linker with lld
* replace GCC with clang
Additionally, RISC-V was promoted to stable so it can be enabled by default in CI.
WARNING: not confirmed to work on real hardware.

riscv: use LLVM tools instead of GNU toolchain

---

main.go
main_test.go
src/runtime/runtime_cortexm_qemu.go
src/runtime/runtime_fe310.go
src/runtime/runtime_fe310_baremetal.go
src/runtime/runtime_fe310_qemu.go
targets/cortex-m-qemu.json
targets/cortex-m-qemu.s
targets/hifive1-qemu.json
targets/hifive1-qemu.ld
targets/riscv.json

With this PR, you can easily debug RISC-V code in QEMU. For example:
```
$ tinygo gdb -target=hifive1-qemu ./testdata/alias.go 
GNU gdb (GDB) 8.2.90.20190228-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=riscv64-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>. …
```

Add support for debugging RISC-V using QEMU

---

cgo/cgo_test.go

Since LLVM 9, CGo sometimes randomly breaks with weird error messages on
Windows. I'm not sure why this is the case, but it might be related to
concurrency.
Disable concurrency for now, and hope that will make the errors go away.
---
This PR is for the issue described here: https://github.com/tinygo-org/tinygo/pull/763#issuecomment-562865172
I'm not sure whether it'll fix it, but I hope so.

cgo: don't run tests in parallel

---

src/machine/spi.go

This allows display drivers like st7789 to be used on the TinyGo Playground.

machine: add Tx method to simulated SPI bus

---

LICENSE
Makefile
README.md
builder/build.go
builder/builtins.go
builder/cc1as.cpp
builder/cc1as.h
builder/clang.cpp
builder/compiler-builtin.go
builder/compiler-external.go

This will be a huge help for people installing TinyGo that don't have LLVM/Clang 9 already installed and in the `$PATH` variable.
Replaces #184.
I added an extra note to the LICENSE part of the README, would that be enough to cover the new code under the different license? I don't think adding it to the LICENSE file would be necessary as the files themselves already say that they are under a different license.

builder: use builtin Clang when building statically

---

builder/builtins.go
targets/riscv.json

This gets all the tests to compile and many of them to pass. There are some issues left, but those are probably unrelated to compiler-rt.
A simple way to test this PR is with the following command:
tinygo run -target=hifive1-qemu ./testdata/float.go
It will fail with a linker error before this PR, and will run successfully after this PR.
Note: this PR will conflict with #769.

riscv: add support for compiler-rt

---

src/examples/systick/systick.go
src/machine/board_arduino.go
src/machine/board_atsamd21.go
src/machine/machine_atmega.go
src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/machine_fe310.go
src/machine/machine_nrf51.go
src/machine/machine_nrf52.go
src/machine/machine_nrf52840.go
src/machine/machine_stm32f103xx.go
src/machine/machine_stm32f407.go
src/runtime/runtime_stm32f103xx.go

These all-caps constants aren't in the Go style, so rename it to `CPUFrequency` (which is more aligned with Go style). Additionally, make it a function so that it is possible to add support for changing the frequency in the future.
Tested by running `make smoketest`. None of the outputs did change.

machine: rename CPU_FREQUENCY -> CPUFrequency()

---

interp/values.go

Accidentally left in the source in https://github.com/tinygo-org/tinygo/pull/787.

interp: remove accidental debug print

---

main_test.go

This change allows all parts of the testing process except for the actual build to be run in parallel. This drastically reduces the time required to run compiler tests. This is a less ambitious version of #641.

Run tests partially in parallel

---

builder/build.go
builder/error.go
compiler/check.go
compiler/errors.go
compiler/optimizer.go

This PR is extracted from #774 and will be useful to resolve a TODO in #782.

compiler: add location information to the IR checker

---

transform/reflect.go

These globals are (and must be!) never modified by the reflect package. By marking them as constant, they will be put in read-only memory. This reduces RAM consumption on microcontrollers.
Discovered while working on #796.

transform: make reflection sidetables constant globals

---

main_test.go

Eventually, open files should be closed when the GC runs and the finalizer is called. However we shouldn't rely on that.
Using `ioutil.ReadFile` instead as it's simpler anyway.

main: avoid leaving files open

---

README.md

I noticed the PineTime DevKit is missing from the list of supported boards/targets. O know it's a devkit and not the final product yet, but I still think it should be included.

added missing pinetime devkit to list of suppoerted boards/targets

---

interp/frame.go
interp/testdata/map.ll
interp/testdata/map.out.ll

Some mapassign operations cannot (yet) be done by the interp package. Implement a fallback mechanism so that these operations can still be performed at runtime. In the future, this might be optimized further where possible.
---
This makes a few more packages importable: go/ast, go/format, go/parser, go/printer, go/scanner, and go/token (but probably all because the common dependency go/token became importable).
Eventually I'd like to add support for running gofmt in the playground (without network request!) but go/printer doesn't yet compile due to missing support for interfaces in map keys.

interp: add runtime fallback for mapassign operations

---

main.go

This PR attempts to do for Windows 10 the same searching for default port and drive name when flashing boards as we are now doing for both Linux and macOS.
EDIT:
Both of these commands work:
```
tinygo flash -target circuitplay-express examples/blinky1
```
and
```
tinygo flash -target arduino-nano33 examples/blinky1
```

flash: use win32 wmi to try to find UF2 and COM ports when flashing

---

azure-pipelines.yml

3 hours is too close to the edge. Extend to 4 hours to make sure a build including LLVM build will finish before the deadline.

ci: increase Azure Pipelines timeout to 4 hours

---

.circleci/config.yml
builder/compiler-builtin.go
builder/env.go

These symlinks are now unnecessary because Clang (and previously lld) have been integrated into TinyGo.

ci: remove symlink creation

---

src/device/riscv/start.S

Now that we've switched to LLVM 9, we don't need a workaround anymore for the 'la' pseudo-instruction.
The assembly is slightly different but should be functionally identical.
Tested locally with the PR in #765.

riscv: improve startup assembly

---

src/runtime/runtime_fe310.go
src/runtime/runtime_fe310_baremetal.go
src/runtime/runtime_fe310_qemu.go

QEMU doesn't support the RTC peripheral yet so work around it for now.
This makes the following command work:
tinygo run -target=hifive1-qemu ./testdata/coroutines.go

riscv: support sleeping in QEMU

---

Makefile
builder/commands.go
cgo/libclang_config.go
compiler/syscall.go
main.go
src/os/file_unix.go
src/runtime/os_freebsd.go
src/runtime/runtime_unix.go

This PR adds initial support for running TinyGo on FreeBSD using self-built LLVM. Both `test` and `smoketest` pass and I'm working on adding it to the ports tree.

Add initial FreeBSD support

---

main.go

Remove this code for two reasons:
1. It is not needed.
2. It breaks `tinygo gdb` for debugging QEMU targets (such as cortex-m-qemu).

main: remove getting a serial port in gdb subcommand

---

compiler/sizes.go

This commit fixes a crash when trying to compile the following (invalid) code:
package main
import "unsafe"
func main() {
}
type Foo struct {
x DoesNotExist
}
const foo = unsafe.Sizeof(Foo{})
This commit fixes this situation. The result is a regular error message, indicating that `DoesNotExist` is not defined.

compiler: don't crash when encountering types.Invalid

---

src/runtime/runtime_wasm.go

This was reported in issue #805.

wasm: implement memcpy and memset

---

src/machine/board_arduino_nano33_baremetal.go

UART2 was configured with the wrong SERCOM for the used pins (PB22 and
PB23). However, after changing the SERCOM from 3 to 5 that led to a
conflict with UART1 (used for the on-board WiFi). But the used pins are
also usable from SERCOM 3, so in the end I switched SERCOM5 and SERCOM3
around.
With this change, I was able to get examples/echo working (after changing the UART to UART2 and changing the used pins to RX0 and TX1). I also verified that the on-board WiFi chip is still usable with the espconsole example in the drivers repo.

machine/arduino-nano33: fix UART1 and UART2

---

cgo/cgo_test.go
cgo/const.go
cgo/const_test.go
cgo/testdata/const.go
cgo/testdata/const.out.go

This doesn't yet support things like `#define foo foo` but that requires more complex compiler changes.

cgo: add support for identifiers

---

compiler/compiler.go
loader/loader.go

Add location information (whenever possible) to failed imports. This helps in debugging where an incorrect import came from.
For example, show the following error message:
/home/ayke/src/github.com/tinygo-org/tinygo/src/machine/machine.go:5:8: cannot find package "foobar" in any of:
/usr/local/go/src/foobar (from $GOROOT)
/home/ayke/src/foobar (from $GOPATH)
Instead of the following:
error: cannot find package "foobar" in any of:
/usr/local/go/src/foobar (from $GOROOT)
/home/ayke/src/foobar (from $GOPATH)

loader: improve error messages for failed imports

---

compiler/compiler.go
compiler/errors.go
go.mod
go.sum

This error can normally only happen with `//go:linkname` and such, but it's nice to get an informative error message in that case.

compiler: improve "function redeclared" error

---

compiler/optimizer.go

This reduces code size in a few cases when tested against the drivers smoketests (although there was one minor increase) without significantly increasing compile time. In fact, in my testing compile time appears to be going down a little bit (around 1%, within the noise).

compiler: add globaldce pass to start of optimization pipeline

---

src/runtime/runtime_atsamd51.go

It was still using the (long removed) `//go:volatile` pragma for volatile variables, thus it was only accidentally working.
Tested with examples/blinky1 on an ItsyBitsy M4.

runtime: fix atsamd51 volatile usage

---

src/machine/machine_atsamd51.go

I found 2 problems with ADC handling for ATSAMD51 boards
1) in InitADC(), 10-bit resolution is being set instead of 12-bit resolution, and ADC.Get() assumes 12 bit resolution
2) The bits denoting which pin to use on an ADC bus are not cleared to be reset on subsequent reads. This causes the first pin that is read on an ADC bus to be the only pin that is ever read on that bus.  Also the "Data Ready" flag was not being cleared properly after the first garbage conversion, which causes inconsistent and incorrect values to be returned.
This PR fixes all described above, and is necessary to complete https://github.com/tinygo-org/tinygo/pull/800

atsamd51: Fixes/Improvements for ADC pins

---

azure-pipelines.yml

Zip files are far more often used on Windows systems, so we provide zip files in releases. Unfortunately, previously the provided artifact in CI was really just a compressed .tar.gz file, which defeats the purpose.
This commit zips the release tarball itself so it can be downloaded as an artifact.

ci: produce zip as artifact in Azure Pipelines

---

interp/frame.go
interp/utils.go
interp/values.go

This commit removes a panic and replaces it with a proper source
location. The message still isn't very helpful, but at least it points
to a location in the source code.
I'm not very happy with all the `err.Error()` calls, but that's the way
to fit this in a `scanner.Error`. Eventually we should make a
replacement for `scanner.Error` that does proper wrapping of the
original error message.

interp: error location for "unknown GEP" error

---

Makefile
README.md
builder/build.go
builder/uf2.go
compileopts/target.go
src/machine/board_circuitplay_bluefruit.go
src/machine/machine_nrf52840.go
targets/circuitplay-bluefruit.json
targets/circuitplay-bluefruit.ld

Add a target for the Adafruit Circuit Playground Bluefruit, which is
based on the nRF52840. Adds the necessary code for the machine
package and the json and linker script files in the targets directory.
The machine package code is based on board_circuitplay_express.go,
with modifications made by consulting the wiring diagram on the
adafruit website here:
https://learn.adafruit.com/adafruit-circuit-playground-bluefruit/downloads
Also adds support to the uf2 conversion packacge to set the familyID
field. The Circuit Playground Bluefruit firmware rejects uf2 files
without the family id set to 0xADA52840 (and without the flag specifying
that the family id is present).

targets: add target circuitplay-bluefruit

---

Makefile
README.md
src/machine/board_pyportal.go
src/machine/machine_atsamd51.go
src/machine/machine_atsamd51g19.go
src/machine/machine_atsamd51j19.go
src/machine/machine_atsamd51j20.go
src/runtime/runtime_atsamd51j20.go
targets/atsamd51j20a.json
targets/pyportal.json

https://www.adafruit.com/product/4116
LED: working
USBCDC: working
UART: not working (however only needed for reprogramming or getting debug output from ESP32)
SPI0: working
I2C: working
I2S: not added/tested yet
Temp sensor: working via tinygo.org/x/drivers/adt7410, pending https://github.com/tinygo-org/drivers/pull/109
Light sensor: working via `machine.ADC{machine.LIGHT} `
Resistive touch: working via github.com/bgould/tinygo-touchscreen
TFT: working via github.com/bgould/drivers/ili9341 (pending https://github.com/tinygo-org/drivers/pull/115)
TFT Backlight: PWM working
Neopixel: working via tinygo.org/x/drivers/ws2812
Wifi: working via tinygo.org/x/drivers/wifinina
QSPI flash: not tested; driver started but needs to get further along to be able to test
~~Also, auto-reset when flashing …

Adafruit PyPortal Support

---

compiler/compiler.go
compiler/symbol.go
go.mod
go.sum

This makes most globals visible from GDB, using `info variables`.
For example, without this PR:
```
$ tinygo gdb -target=cortex-m-qemu ./testdata/gc.go
[...]
(gdb) info variables
All defined variables:
Non-debugging symbols:
0x20001000  ./testdata/gc.go.xorshift32State
0x20001000  _globals_start
0x20001000  _sdata
0x20001004  _edata
0x20001010  _sbss
0x20001010  runtime.zeroSizedAlloc
0x20001014  runtime.nextAlloc
0x20001018  runtime.endBlock
0x20001019  runtime.poolStart
0x2000101c  ./testdata/gc.go.randSeeds
0x20001030  ./testdata/gc.go.scalarSlices
0x20001060  _ebss
0x20001060  _globals_end
0x20001060  _heap_start
```
With this PR:
```
$ tinygo gdb -target=cortex-m-qemu ./testdata/gc.go
[...]
(gdb) info variables
All defined variables:
File src/runtime/baremetal.go:
void *_globals_end; …
```

compiler: add support for debugging globals

---

compiler/compiler.go
compiler/inlineasm.go
src/device/riscv/csr.go
src/device/riscv/start.S
src/runtime/runtime_fe310.go
src/runtime/runtime_fe310_baremetal.go
src/runtime/runtime_fe310_qemu.go
targets/riscv.ld

This too me a looong time to figure out between compiler bugs, few examples, and a small typo that cost me hours (`ret` vs `mret`).
You can now run the blinky2 example in QEMU and on the HiFive1b hardware:
```
tinygo run -target=hifive1-qemu examples/blinky2
tinygo flash -target=hifive1b examples/blinky2
```

RISC-V interrupts

---

src/runtime/runtime_fe310.go

This can be useful for debugging critical bugs in code. I haven't added human-readable exceptions (such as "illegal instruction" or "stack overflow") yet, they can be added when they happen in practice (to avoid increasing code size unnecessarily).
A program like this:
```go
// ...
riscv.Asm(".long 0") // undef
// ...
```
will cause an error like the following:
fatal error: exception with mcause=2 pc=0x204002ce
where code 2 means "illegal instruction" according to the RISC-V docs (as expected).
Tested both on hardware (HiFive1 rev B) and in QEMU.

riscv: print exception PC and code

---

src/machine/board_digispark.go

This PR adds the clock speed and pin mappings to the existing Digispark board definition.

machine/digispark: add clock speed and pin mappings

---

src/machine/board_feather-m4.go
src/machine/board_itsybitsy-m4.go
src/machine/board_metro-m4-airlift.go
src/machine/board_pybadge.go
src/machine/machine_atsamd51.go

This commit does the same thing as https://github.com/tinygo-org/tinygo/pull/597 but for samd51 series chips. Pin mode and pad numbers are automatically calculated from pin numbers, returning an error if no valid pinout is possible.
Code that uses SPI1 and code that does not configure all pins (for example, leaving out MISO) may need to be updated. Therefore, I think it's best to merge this after the coming release to have a bigger chance of finding bugs. Also, it should be updated after #800 has been merged.

machine/atsamd51: refactor SPI pin configuration to only look at pin numbers

---

src/machine/board_pyportal.go

This PR corrects the SPI pin mapping in the PyPortal board so that it builds correctly now that #802 has been merged.

machine/pyportal: remove manual SPI pin mapping as now handled by defaults

---

compileopts/target.go
main.go
targets/hifive1b.json

This makes debugging on the HiFive1 rev B much easier:
tinygo gdb -target=hifive1b examples/echo

hifive1b: add support for gdb subcommand

---

compileopts/config.go
compiler/compiler.go
goenv/goenv.go

This should fix #771. Not sure how to test it, but you can test locally by running tinygo with the ./testdata/cgo package with the following extra file (main2.go):
```go
// +build !cgo
package main
func main() {
println("no cgo")
}
```
and run with `CGO_ENABLED` set to `1` or `0` to test the difference.

compiler: add support for CGO_ENABLED environment variable

---

main_test.go

This caused most tests to run the zeroalloc.go test instead of what they should have been tested, and in turn explains most of the performance gains of parallel testing.
This commit fixes it by avoiding race conditions. Luckily, no tests started failing since then due to this.
@jaddr2line

main: fix race condition in tests

---

builder/builtins.go
targets/gameboy-advance.json

This avoids errors like the following:
ld.lld-9: error: undefined symbol: __umodsi3
ld.lld-9: error: undefined symbol: __aeabi_uidivmod

gameboy-advance: include compiler-rt in build

---

src/machine/usb.go

This greatly cuts down on compile time (by about 5x for small programs) and also makes the program a whole lot smaller. Overall it cuts down `make smoke-test` in the drivers repository by half (from 160s to 80s).
This will probably also fix the timeout issue in the Playground: https://github.com/tinygo-org/playground/issues/7

machine: avoid bytes package in USB logic

---

src/machine/machine_atsamd51.go

This is a combination of 3 commits. The first was to get UART1 working at all. The second was something that looked like an obvious bug - but I didn't test whether I2C still works. The third is what this PR is all about. Here is the commit message:
```
A small footnote in the datasheet says that interrupt source numbers
correspond to the bit position in INTFLAG. We only need the RXC
interrupt for UART. In other words, ony the _2 interrupts (RXC is in the
2nd bit position) needs to be used for UART to work correctly.
In the future, more interrupts may be needed. They can then be added as
necessary.
```
(This PR is here to make #782 easier to complete).

Improve UART interrupts on atsamd51

---

targets/arduino.json

On Windows, it is common that there is a colon in the path. `avrdude` will treat that as a separator and everything behind it as the file format specifier instead of defaulting to Intel hex format.
By explicitly specifying the Intel hex format (with `:i`), this issue should be fixed.
fixes #851 (hopefully)

arduino: make avrdude command line compatible with Windows

---

src/machine/board_feather-m4.go
src/machine/board_itsybitsy-m4.go
src/machine/board_metro-m4-airlift.go
src/machine/board_pybadge.go
src/machine/board_pyportal.go
src/machine/machine_atsamd51.go

With this change, it's no longer necessary to set a specific pin mode: it will get autodetected in the `Configure()` call.
Tested on an ItsyBitsy M4 with the mpu6050 example in the drivers repo.

machine/samd51: refactor i2c pin handling to auto-detect pin mode

---

.circleci/config.yml
.gitmodules
Makefile
azure-pipelines.yml
src/runtime/runtime_wasm.go
targets/wasm.json

This allows CGo code to call some libc functions.
Fixes part of #844.

wasm: include wasi-libc

---

azure-pipelines.yml

The wasi-libc Makefile uses the `find` command line tool. Unfortunately, it was using the Windows find version instead of the MinGW version, leading to lots of errors at a later stage.
This commit prepends /usr/bin to `$PATH` to make sure the MinGW version is found first.

ci: fix Windows build failure for wasi-libc

---

compiler/compiler.go
compiler/map.go
src/runtime/hashmap.go
testdata/map.go
testdata/map.txt

This implementation simply casts types without special support to an interface, to make the implementation simpler and possibly reducing the code size too. It will likely be slower than the canonical Go implementation though (which builds special compare and hash functions at compile time).

Support maps with arbitrary key types

---

Makefile
src/runtime/gc_conservative.go
targets/avr.S
targets/avr.json
targets/avr.ld
testdata/gc.go

This might sound crazy, but I think it's better to enable the GC by default to avoid surprises. It costs 1130 bytes of flash and 16 bytes of RAM (plus heap overhead) so it's not exactly free, but if needed it can easily be disabled with `-gc=leaking`. On the Uno (32kB flash, 2kB RAM) that's not massive, on the DigiSpark (8kB flash, 0.5kB RAM) that may be too much depending on the application.
Also added a smoke test for the `-gc=leaking` case: "if it isn't tested, it's broken".

avr: use a garbage collector

---

src/runtime/arch_wasm.go
src/runtime/baremetal.go
src/runtime/runtime_arm7tdmi.go
src/runtime/runtime_cortexm.go
src/runtime/runtime_fe310.go

This is the same problem as in https://github.com/tinygo-org/tinygo/pull/605, but other targets also suffer from it.
Discovered with the GBA target, but as pointed out in https://bugs.llvm.org/show_bug.cgi?id=42881#c1 this appears to be a bug in the way external globals are declared, not in LLVM. Therefore I decided that fixing it everywhere would be the best thing to do.

runtime: fix external address declarations

---

src/machine/machine_gameboyadvance.go
src/runtime/interrupt/interrupt_gameboyadvance.go
src/runtime/runtime_arm7tdmi.go
targets/gameboy-advance.ld
targets/gameboy-advance.s

This is based on #860.
By using the same vectoring method as RISC-V uses, this interrupt system does not need any RAM to store the interrupt vector table. Instead, it is implemented by the compiler as a big switch statement.
Other than that, this interrupt system is very bare bones. More features (such as priorities) could be added later if needed. However, I think it would be a good idea to consider interrupt priorities on RISC-V at the same time as the interrupt systems are very similar so that at least the design can be shared.
@kylelemons

GBA interrupts

---

src/runtime/bytes.go

This PR copies the indexBytePortable function from the standard library to fix a linker error similar to the one in https://github.com/tinygo-org/tinygo/issues/154

Added indexBytePortable from standard library to link as implementation for internal/bytealg.IndexByte

---

src/runtime/runtime_wasm.go
targets/wasm_exec.js

This allows TinyGo-built binaries to run under wasmtime, for example:
tinygo build -o test.wasm -no-debug -target=wasm examples/test
wasmtime run test.wasm 0
Of course this doesn't bring full wasi compliance, but it's a start.

wasm: use wasi ABI for basic startup/stdout

---

Makefile
README.md
src/machine/board_clue_alpha.go
targets/clue_alpha.json

https://www.adafruit.com/clue
They note that this is an alpha release of the board and that the pinout/sensors could change, so I've named this target "clue_alpha" in case such changes do occur.

Adding Adafruit CLUE Alpha

---

src/machine/machine_nrf.go

Fixes a typo which made pins configured with `PinInputPulldown` on nRF SoCs not work correctly.

nRF: fix PinInputPulldown

---

src/runtime/volatile/register.go

Allow multiple bit setting on a register, with masking.
Related to https://github.com/tinygo-org/tinygo/issues/777

include ReplaceBits method

---

Makefile

This PR fixes #882 by checking for both variants of command names - with and without the version number suffix. This also uses a more correct detection method than was previously used for ccache.

Autodetect llvm-ar and llvm-nm commands

---

.gitmodules

This reverts back to the upstream repository which has merged all necessary updates (including https://github.com/posborne/cmsis-svd/pull/85 and https://github.com/posborne/cmsis-svd/pull/93).

main: update cmsis-svd module

---

src/machine/buffer.go

The volatile pragma has long since been replaced by builtins, so this commentis now outdated.
See: https://github.com/tinygo-org/tinygo/issues/151#issuecomment-588023760

machine: remove old comment on volatile behavior

---

src/machine/usb_nrf52840.go
src/machine/usb_nrf52840_reset_none.go
src/machine/usb_nrf52840_reset_uf2.go
targets/circuitplay-bluefruit.json
targets/clue_alpha.json

This PR depends on https://github.com/tinygo-org/tinygo/pull/883, and should be rebased once that one is merged.  It implements the functionality for auto-resetting into the UF2 bootloader when a 1200 baud signal is received.
I protected this functionality with build tags since it depends on the UF2 bootloader, and also to enable disabling this functionality if desired.  If preferable however it could be included in the firmware by default without build tags.

1200 baud auto-reset over USB for nrf52840

---

transform/gc.go
transform/testdata/gc-globals.ll
transform/testdata/gc-globals.out.ll

We are currently tracking constant globals with the garbage collector, which is incorrect behavior. If a value is pointed to by a constant global, then it must either be another global or a constant user-defined address (which is not part of the heap). I discovered this because it was breaking optimizations in #910, and caused a size regression.

Do not track const globals

---

compiler/compiler.go

This marks the libc function `abort` as non-returning. This allows LLVM to optimize away code after panics. Also, this allows deadlocks to be properly propogated with the `coroutines` scheduler.

Mark abort as noreturn

---

compiler/check.go

This PR comes with two commits. The first one might be useful in general (and perhaps be submitted separately). The second one should not be merged now, but only after all non-static allocas are avoided in TinyGo (after at least #773 and #745 have been merged).

Check for non-static allocas

---

targets/cortex-m.json

Previously this was set to `arm-none-eabi-gdb`, but that has been replaced by `gdb-multiarch` in recent Debian/Ubuntu versions.

main: use gdb-multiarch for debugging Cortex-M chips

---

targets/atmega328p.json
targets/digispark.json

This commit adds support for running both the Arduino Uno and the
DigiSpark under a simulator.
Running `tinygo gdb` under a simulator is different from (for example)
what `tinygo gdb` does for other boards such as the PCA10040. However, I
think this is the better option as probably very few people actually
have a hardware debugger and supporting GDB with the simulator is then
much more useful.

avr: support `tinygo run` with simavr

---

main.go

This replaces a panic with an informative error message if the right tool (such as OpenOCD) is not installed.

main: check for error after starting the OCD daemon

---

main.go
targets/gameboy-advance.json

With this patch I was able to run `tinygo gdb -target=gameboy-advance -size=short examples/gba-display`.
This also changes the standard mGBA from the Qt frontend to the SDL frontend, because `-g` appears to be broken with the Qt backend (@endrift). I'm not sure whether that's a good idea, but keeping `tinygo run` and `tinygo gdb` consistent seems reasonable to me.

gameboy-advance: enable debugging with GDB

---

compiler/map.go
src/runtime/hashmap.go
testdata/map.go
testdata/map.txt

The index expression and delete keyword are valid on nil maps, so the runtime must be modified to support this.
This is one of the things necessary for JSON support.

compiler,runtime: support operations on nil map

---

compiler/defer.go
testdata/calls.go
testdata/calls.txt

Previously using defer with an exported function generated an invalid function call due to differences between TinyGo's calling convention and the C calling convention.

compiler: fix deferred calls to exported functions

---

.circleci/config.yml
Makefile
azure-pipelines.yml

This makes the `make wasi-libc` command much more reliable and makes the CI configuration simpler. Also, it avoids warnings when they are not relevant.
Now let's hope CI will accept this.

Makefile: fix LLVM tools detection for wasi-libc

---

src/machine/machine_atsamd51.go

I tested the PB04 (A7 on the pybadge), according to the datasheet PB05-PB06-PB07 should work too but I can't say I fully understand it ¯\_(ツ)_/¯

added support for ADC1 on atsamd51 (PB04 / PB05 / PB06 / PB07)

---

.circleci/config.yml

This fixes an error like the following:
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
Apparently apt.llvm.org has been switched over to HTTPS. One solution could be to install apt-transport-https, but another (easier) solution is to switch to a newer container.
Note: I did not switch the other containers, to make sure TinyGo is still built with an older Debian release. That ensures the resulting binaries are relatively portable across distros, even relatively old distros.

ci: move Go version tests to buster containers

---

src/runtime/slice.go

The copy builtin is defined as follows by the Go language spec:
copy(dst, src []T) int
copy(dst []byte, src string) int
In other words, it returns an `int`. The `runtime.sliceCopy` compiler intrinsic returned a `uintptr` instead, which led to a problem while compiling the strings package for AVR.
No other architecture should be affected by this change as the conversion from an `uintptr` to an `int` is a no-op on most architectures.

runtime: return the correct type from the copy builtin

---

compiler/asserts.go
compiler/channel.go
src/runtime/panic.go
testdata/channel.go

This commit makes channel code compilable on AVR, for when goroutines are supported on that platform. I have in fact managed to get initial support for channels working with this patch on a local branch that adds support for the stack-based scheduler.

runtime: fix channels on AVR

---

targets/arm.ld

There were a few instances like `.text` and `.text*`. The first was redundant with the second, but the intention was to write `.text.*`.
This doesn't change anything (tested with `make smoketest`) but should avoid propagating this error in the future.
See: https://github.com/tinygo-org/tinygo/pull/863#discussion_r386060173

arm: fix linker script

---

main.go
main_test.go

This commit switches integration tests to use the same error reporting
mechanism as the tinygo compiler normally uses. It replaces errors like
this:
main_test.go:139: failed to build: interp: branch on a non-constant
With this:
main.go:693: # math/rand
main.go:695: interp: branch on a non-constant
In this particular case the error isn't much better (it gives the
relevant package, though) but other errors should also include the
source location where they happen.

main: improve error reporting while running go test

---

go.mod
go.sum

This doesn't really change anything but might make packaging easier on Fedora.
See: https://github.com/tinygo-org/go-llvm/pull/14

main: update go-llvm dependency

---

Dockerfile

This PR adds the use of the `git submodule sync` command in the docker dev build to handle case where repo url changes, which fixes the broken dockerhub builds:
https://hub.docker.com/repository/registry-1.docker.io/tinygo/tinygo-dev/builds/2c37af2e-b3c7-4718-bb87-fe145312ad44

docker: use git submodule sync to fix broken docker dev build

---

src/internal/task/task_stack_cortexm.go
src/runtime/gc_conservative.go
src/runtime/gc_leaking.go
src/runtime/gc_none.go
src/runtime/runtime_arm7tdmi.go
src/runtime/runtime_atsamd21.go
src/runtime/runtime_atsamd51.go
src/runtime/runtime_avr.go
src/runtime/runtime_cortexm_qemu.go
src/runtime/runtime_fe310.go
src/runtime/runtime_nrf.go
src/runtime/runtime_stm32.go
src/runtime/runtime_unix.go
src/runtime/runtime_wasm.go
src/runtime/scheduler_any.go
src/runtime/scheduler_none.go

This PR is based on top of #828, and generalizes the "none" scheduler to work on platforms other than AVR. It should now work on all platforms except WebAssembly. Init should also be run in the main goroutine when using a scheduler, but this is not yet possible as the runtime must be initialized before starting a goroutine.

Generalize -scheduler=none to support most platforms

---

cgo/cgo.go
cgo/testdata/flags.go
cgo/testdata/flags.out.go
cgo/testdata/include/foo.h

This is very useful for (conditionally) adding extra include paths relative to the package path.

cgo: make -I and -L paths absolute

---

Makefile

This allows setting a different directory for experimental changes. For example, I also have a llvm-project.master directory that tracks the master branch. It is very useful to be able to temporarily use that directory:
make llvm-build.master LLVM_BUILDDIR=llvm-build.master LLVM_PROJECT=llvm-project.master

Makefile: allow overriding the llvm-project directory

---

src/machine/board_arduino_nano33.go
src/machine/board_circuitplay_bluefruit.go
src/machine/board_circuitplay_express.go
src/machine/board_clue_alpha.go
src/machine/board_feather-m0.go
src/machine/board_feather-m4.go
src/machine/board_itsybitsy-m0.go
src/machine/board_itsybitsy-m4.go
src/machine/board_metro-m4-airlift.go
src/machine/board_nrf52840-mdk.go
src/machine/board_particle_argon.go
src/machine/board_particle_boron.go
src/machine/board_particle_xenon.go
src/machine/board_pca10056.go
src/machine/board_pybadge.go
src/machine/board_pyportal.go
src/machine/board_reelboard.go
src/machine/board_trinket.go
src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/usb.go
src/machine/usb_nrf52840.go

The PR sets the vid and pid to valid values supplied by Adafruit and Arduino for boards that support USB CDC.
It might be able to help Windows 10 users get their devices to auto-mount as USB CDC without special drivers. cc/ @torntrousers

machine/usb: set the vid and pid to valid values supplied by Adafruit and Arduino

---

azure-pipelines.yml

This PR specifies to use go1.13.8 instead of the Azure image default which is now go1.14 for MS Azure pipeline builds.

build: use go1.13.8 for MS Azure

---

Makefile
src/internal/task/task_stack_avr.go
src/runtime/scheduler_avr.S
targets/avr.json

This adds support for the `-scheduler=tasks` flag for AVR. On most AVR chips you wouldn't want to run a real scheduler but it may be useful in some cases, especially on devices with more RAM. It is disabled by default.

avr: add support for tasks scheduler

---

targets/avr.ld

This convention is followed by most of the avr-gcc toolchain but older versions of binutils don't mind overlapping program/data spaces. However, newer versions start complaining about an overlap in address space:
avr-ld: section .stack VMA [0000000000000100,00000000000002ff] overlaps section .text VMA [0000000000000000,0000000000000225]
This commit moves the data space in the linker script to 0x800000, like the rest of the AVR toolchain assumes.
Tested:
* examples/serial and examples/echo on the Arduino Uno
* examples/blinky1 on the Digispark

avr: move data address space to 0x800000

---

interp/frame.go
interp/interp_test.go
interp/testdata/interface.ll
interp/testdata/interface.out.ll
testdata/interface.go

This is needed for compiling math/rand on Go 1.14 (but it is not a complete solution).
Non-constant type asserts are not yet implemented, but should be relatively easy to add at a later time. They should result in a clear error message for now.

interp: add support for constant type asserts

---

src/machine/machine_stm32f103xx.go

This PR corrects #973 by enabling the clock when a GPIO pin is configured.

machine/stm32f103xx: enable clock on configure of GPIO pin

---

src/machine/board_stm32f4disco.go
src/machine/machine_stm32_moder_gpio.go
src/machine/machine_stm32_uart.go
src/machine/machine_stm32f103xx.go
src/machine/machine_stm32f407.go

Step 2 of #777 : UART code cleanup
Moving the common parts of the STM32F1xx and STM32F4xx UART setup into a separate file, and simplifying the chip-specific pieces.

refactor stm32 UART code

---

targets/atmega1284p.json

Somehow I forgot to add this emulator. With this, you can easily emulate programs:
$ tinygo run -target=atmega1284p examples/serial
Loaded 698 .text at address 0x0
Loaded 12 .data
hello world!..
hello world!..
hello world!..

avr: add emulator to atmega1284p

---

main_test.go

This should avoid the rather frequent "test ran too long, terminating..." error message that often occurs in CI and when running `go test` manually. Apparently I was too optimistic: some tests take longer than 1 second to run.

main: extend test timeout from 1s to 10s

---

src/machine/board_particle_argon.go
src/machine/board_particle_boron.go
src/machine/board_particle_xenon.go

Set the USB VID, PID and product names to the same ones as used by Particle.

Set USB CDC identifiers to Particle ones

---

interp/scan.go
interp/scan_test.go
interp/testdata/scan.ll

This commit teaches the interp scanner that supported interface operations (type assertions, interface assertions) are supported.
This fixes a problem with math/rand in Go 1.14. The change is simple but it took me quite some time to figure out.

interp: better support interface operations

---

transform/interface-lowering.go
transform/interface-lowering_test.go
transform/optimizer.go

Panics are bad for usability: whenever something breaks, the user is shown a (not very informative) backtrace. Replace it with real error messages instead, that even try to display the Go source location.
(This PR is only for the interface lowering pass, other passes can be done later as needed).

transform: replace panics with source locations

---

Dockerfile

The headerfile for picolibc gets copied into the Dockerfile early on during its build, but then removed immediately afterwards when pulling in the subprojects, causing a compilation error when trying to build `.hex` files using hte Docker image.

Copy picolibc header into Dockerfile

---

transform/interface-lowering.go

It appears that LLVM can sometimes recognize that multiple calls to `runtime.interfaceMethod` can be merged into one. When that happens, the interface lowering pass shows an error as it didn't expect that situation.
Luckily the fix is very easy. Simply iterate over all the call instructions instead of assuming there is only one.
Fixes https://github.com/tinygo-org/tinygo/issues/984

transform: fix error in interface lowering pass

---

src/machine/board_digispark.go
src/machine/machine_attiny.go
src/machine/machine_attiny85.go

Add definitions for constants like PB0.
This was originally based on #957 but as long as I can't get that chip to work, I'll post the cleanup here anyway.
Note: I've started pin numbers (like `PB0`) from 0 instead of 8 because there is only one port on the attiny85. It saves 14 bytes of code for blinky1.

avr: clean up ATtiny definitions

---

builder/build.go
compiler/asserts.go
compiler/calls.go
compiler/channel.go
compiler/compiler.go
compiler/defer.go
compiler/errors.go
compiler/func.go
compiler/gc.go
compiler/goroutine.go
compiler/inlineasm.go
compiler/interface.go
compiler/interrupt.go
compiler/llvm.go
compiler/map.go
compiler/symbol.go
compiler/syscall.go
compiler/volatile.go

Work-in-progress to refactor the compiler.
Not nearly finished, but sharing here for initial review to make sure this is the right direction. The main goal is to remove `Compiler.builder`, which is almost like a global variable (shared throughout the entire compiler instance). Instead, an IR builder should be made per function. This will make the structure of the compiler a lot simpler and should avoid lots of jumping around, for example to create wrapper functions. The last time I tried to remove the `SimpleDCE` mechanism (a blocker for building packages independently), wrapper functions were a major pain and resulted in needing to add a worklist for functions to be built after the current one is finished.
This change will be huge, so I decided to split it in many steps to make it …

Refactor compiler

---

main_test.go
src/runtime/runtime_fe310.go
src/runtime/runtime_tinygoriscv.go
src/runtime/runtime_tinygoriscv_qemu.go
targets/riscv-qemu.json
targets/riscv-qemu.ld

This allows running RISC-V tests in CI using QEMU, which should help catch bugs.
This PR is an improvement over #765 in that it doesn't hack around the lack of a test finisher but instead uses a new target (`-target=riscv-qemu`) that is based on VirtIO and actually includes a way to exit the QEMU process.

riscv: implement VirtIO target

---

compiler/asserts.go
compiler/calls.go
compiler/compiler.go
compiler/func.go
compiler/interface.go
compiler/volatile.go
src/runtime/panic.go
transform/func-lowering.go
transform/optimizer.go
transform/testdata/func-lowering.ll
transform/testdata/func-lowering.out.ll

Finally, I think this branch is ready.
The first three commits are commits to prepare for the change in the fourth commit, which is what this PR is about. They make sure escape analysis won't regress after `runtime.isnil` has been removed.
I found exactly one regression in escape analysis: in testdata/calls.go, but only on a host OS and on WebAssembly. Further investigation revealed that it has something to do with function pointers or closures.
Most tests I've done (including smoke tests) result in a reduction of code size however some get bigger (perhaps because the inliner made different choices somewhere). None of the baremetal tests resulted in an escape analysis regression. Overall I think this is an improvement.
(Note that the GitHub ordering of commits is wrong, they're sorted by …

Remove runtime.isnil

---

src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/usb_nrf52840.go

Somehow moving to LLVM memory intrinsics for calls like memcpy made the
machine.sendUSBPacket get inlined. This is a problem because it is
called in many different functions and it is just big enough to cause a
significant file size increase.
Adding //go:noinline solves this problem and gets the examples/blinky1
program below the file size it was before this change (tested:
itsybitsy-m0, itsybitsy-m4, circuitplay-bluefruit).
This PR fixes the binary size regression seen in #995.

machine: avoid binary size regression after LLVM memory intrinsics

---

compiler/compiler.go
compiler/intrinsics.go
src/reflect/value.go
src/runtime/runtime.go

Use LLVM intrinsics for memory operations (`memset`, `memcpy`, `memmove`). This gives more information to the optimizer and in the end lowers to libc functions instead of a custom TinyGo implementation. This is possible since #871 and #845.
Another motivation for this PR is to reduce the amount of code at the end of the `compiler.Compile` function, which should help with eventually breaking it down further into per-package compiles (#285).

LLVM memory builtins

---

compiler/asserts.go
compiler/compiler.go
interp/frame.go
src/runtime/panic.go
testdata/binop.go
testdata/binop.txt

Previously, the compiler used LLVM's shift instructions directly, which have UB whenever the shifts are large or negative. This commit adds runtime checks for negative shifts, and handles oversized shifts.

compiler: implement spec-compliant shifts

---

compiler/compiler.go
ir/passes.go

This commit modifies the SimpleDCE pass to emit errors similar to those emitted by gc when the main function is missing.
gc's output:
```
runtime.main_main·f: function main is undeclared in the main package
```
our output (after this commit):
```
error: function main is undeclared in the main package
```

ir: add descriptive error messages to SimpleDCE pass

---

compiler/compiler.go
interp/errors.go
interp/frame.go
interp/interp.go
interp/scan.go
main.go

This should make it much easier to figure out why and where an error happens at package initialization time.
Example error:
```
../../../../../../usr/local/go/src/regexp/syntax/parse.go:1535:5: interp: branch on a non-constant
traceback:
../../../../../../usr/local/go/src/regexp/syntax/parse.go:774:28:
%107 = call { %runtime._string, %runtime._interface } @"(*regexp/syntax.parser).parseClass"(%"regexp/syntax.parser"* %23, i8* %105, i32 %106, i8* undef, i8* undef), !dbg !2008
../../../../../../usr/local/go/src/regexp/regexp.go:170:25:
%8 = call { %"regexp/syntax.Regexp"*, %runtime._interface } @"regexp/syntax.Parse"(i8* %6, i32 %7, i16 %2, i8* undef, i8* undef), !dbg !1916
../../../../../../usr/local/go/src/regexp/regexp.go:133:16:
%6 = call { %regexp.Regexp*, %runtime._interface } …
```

interp: show backtrace with error

---

compiler/interface.go
testdata/interface.go
testdata/interface.txt

This is used for example by the errors package, which contains:
if x, ok := err.(interface{ As(interface{}) bool }); ok && x.As(target) {
return true
}
The interface here is not a named type.

compiler: add support for anonymous type asserts

---

src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/usb.go
src/machine/usb_nrf52840.go

This PR corrects the USB CDC composite descriptors for the ATSAMD21, ATSAMD51, and NRF52840 processors.
Turns out that the clues provided by @sago35 were correct, the descriptor needed to be changed.
I tested the `example/echo` program with these boards: 
- Circuit Playground Express
- ItsyBitsy M4
- Circuit Playground Bluefruit
On these OS:
- Ubuntu
- macOS
- Windows 10.

machine/atsamd21,atsamd51,nrf52840: correct USB CDC

---

compileopts/config.go
main.go
src/runtime/gc_extalloc.go
src/runtime/gc_globals_conservative.go
src/runtime/gc_globals_precise.go
src/runtime/gc_stack_portable.go
src/runtime/gc_stack_raw.go
src/runtime/runtime_unix.go
src/runtime/runtime_unix_heap.go
src/runtime/runtime_unix_noheap.go
transform/coroutines.go

In cases where tinygo is running in an environment that it does not own, it may be desirable to allow tinygo to use a C heap. This is accomplished by prepending treap nodes to the beginning of every allocation.
Marking a node is implemented by removing it from the treap and then pushing it onto a scan queue (which is implemented as a linked list using the memory previously used for the treap node). Nodes are then popped off of this queue, scanned, and then pushed onto a new treap. Once the queue is empty, all currently active nodes will have been moved from the old treap to the new treap. All nodes from the old treap are then destroyed, and the new treap is swapped in.
All operations are done non-recursively. This is still somewhat WIP, and there is a lot of debugging code still left in …

Add garbage collector that uses an external allocator

---

compiler/gc.go

Before this commit, the garbage collector was able to collect string values while they were still in use.

compiler: track the result of string concatenation

---

compiler/compiler.go
transform/gc.go
transform/testdata/gc-stackslots.ll
transform/testdata/gc-stackslots.out.ll

As demonstrated in #1009, allocations are sometimes released too early because the stack slot is hit multiple times. This PR attempts to fix this by generating separate stack slots for PHI nodes.

track phi nodes in stack slots

---

compiler/compiler.go
compiler/goroutine.go

In an effort to add debug info to _all_ functions, this PR adds debug information to goroutine start wrappers.

compiler: add debug info to goroutine start wrappers

---

src/examples/systick/systick.go
src/examples/wasm/README.md
src/examples/wasm/export/wasm.go
src/internal/task/task_coroutine.go
src/machine/machine_generic.go
src/runtime/arch_wasm.go
src/runtime/math.go
src/runtime/panic.go
src/runtime/runtime_arm7tdmi.go
src/runtime/runtime_atsamd21.go
src/runtime/runtime_atsamd51.go
src/runtime/runtime_avr.go
src/runtime/runtime_cortexm.go
src/runtime/runtime_cortexm_qemu.go
src/runtime/runtime_fe310.go
src/runtime/runtime_nrf.go
src/runtime/runtime_stm32.go
src/runtime/runtime_tinygoriscv_qemu.go
src/runtime/runtime_unix.go
src/runtime/runtime_wasm.go
src/syscall/syscall_darwin.go
src/syscall/syscall_libc.go
testdata/calls.go

This is the kind that is used in Go (actually CGo) for exporting functions. I think it's best to use `//export` instead of our custom `//go:export` pragma, for consistency (they are equivalent in TinyGo). Therefore I've updated all instances to the standard format, except for two that are updated in https://github.com/tinygo-org/tinygo/pull/1024.
No smoke tests changed (when comparing the output hash), except for some wasm tests that include DWARF debug info and tend to be flaky anyway. Therefore this should be safe to apply.

all: change //go:export to //export

---

src/internal/task/task_coroutine.go
src/internal/task/task_none.go
src/internal/task/task_stack.go
src/runtime/gc_stack_raw.go
src/runtime/scheduler_avr.S
src/runtime/scheduler_cortexm.S
src/runtime/scheduler_tinygoriscv.S
targets/riscv.json

Before this PR, some allocations on baremetal would not be tracked by the garbage collector while in use. This is because the only location that they were stored in at the time that the GC was invoked was in a callee-saved register. This PR works around the problem by pushing all callee-saved registers onto the active stack before scanning it.

runtime (gc): scan callee-saved registers while marking stack on baremetal

---

src/device/arm/arm.go
src/machine/i2c.go
src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/machine_fe310.go
src/machine/machine_stm32f103xx.go
src/machine/uart.go
src/machine/usb.go

Calling `errors.New` in an error path causes a heap allocation at an already unfortunate moment. It is more efficient to create these error values in globals and return these constant globals. If these errors are not used (because the related code was optimized out), the globals will also be optimized out.
Feel free to suggest more (or less) precise error messages, I haven't put much thought in which errors should be merged and which shouldn't.
---
This commit also helps avoid a possible recursive code path: `runtime.alloc` may print an error message when the heap is full but the USB-CDC code to print it may also cause an allocation to happen.

machine: move errors.New calls to globals

---

Makefile
builder/builtins.go
builder/library.go
builder/picolibc.go
src/runtime/runtime_tinygoriscv_qemu.go
targets/cortex-m.json
targets/gameboy-advance.json
testdata/cgo/main.c
testdata/cgo/main.go
testdata/cgo/main.h
testdata/cgo/out.txt

A collection of somewhat related changes.
1. A fix to get hifive1-qemu to compile again (oops!).
2. Use `-fshort-enums` consistently.
3. Omit frame pointers on ARM.
The main reason to omit frame pointers is that it makes it easier for me to recover stack usage from DWARF call frame information.

Omit frame pointer

---

src/runtime/gc_conservative.go

This PR attempts to fix #436 and hopefully reduce stack usage.
The GC modifications take a similar approach to the MicroPython GC, in that a fixed-size stack is used to track allocations that need to be scanned. If the stack overflows, this forces a full rescan of all marked allocations. This is potentially a lot slower in some extreme cases, but does not blow up the stack like the current version does.
This seems to pass some basic sanity checks, but we should try this out with some larger tinygo programs before merging it.

runtime (gc): remove recursion from "conservative" GC

---

compiler/defer.go
compiler/interface.go
testdata/calls.go

Previously, the typecode was passed via a direct reference, which results in invalid IR when the defer is not reached in all return paths. It also results in incorrect behavior if the defer is in a loop, causing all defers to use the typecode of the last iteration.

compiler: pass interface typecode through defer frames

---

.circleci/config.yml
Dockerfile
Makefile
README.md
azure-pipelines.yml
builder/cc1as.cpp
builder/cc1as.h
builder/clang.cpp
builder/commands.go
builder/lld.cpp
builder/sizes.go
cgo/libclang.go
cgo/libclang_config.go
cgo/libclang_config_llvm9.go
cgo/libclang_stubs.c
go.mod
go.sum
loader/loader.go
main.go
transform/testdata/allocs.out.ll
transform/testdata/coroutines.out.ll
transform/testdata/func-lowering.out.ll
transform/testdata/gc-stackslots.out.ll
transform/testdata/interface.out.ll
transform/testdata/interrupt-avr.out.ll
transform/testdata/interrupt-cortexm.out.ll
transform/testdata/wasm-abi.out.ll
transform/transform_test.go

This commit also adds a bit of version independence, in particular for external commands. It also adds the LLVM version to the `tinygo version` command, which might help while debugging.
~TODO: make TinyGo work with LLVM version 9 too, for Fedora (and perhaps other distributions). I'm making a PR now so that I can see whether the Windows build will work.~ done

main: switch to LLVM 10

---

Makefile
targets/nrf51.json
targets/nrf52840.json
targets/reelboard-s140v7.json

Unfortunately, `tinygo flash` doesn't work. You have to merge the SoftDevice and the application hex with a mergehex tool and flash that to the board.
Replaces #970.

reelboard: add SoftDevice target reelboard-s140v7

---

.circleci/config.yml
Dockerfile
azure-pipelines.yml
builder/config.go
cgo/cgo_test.go
cgo/testdata/types.out.go
main_test.go
targets/wasm_exec.js

This is a continuation of #901. I have modified the PR of @QuLogic to include the bits needed to get all tests to run on Go 1.14 and extended it a bit to switch to Go 1.14 entirely.
Note that this PR drops support for WebAssembly on Go 1.13 (at least when you import the syscall/js package) but I think working around that would be difficult. It should definitely be possible to create a workaround (for example, by exporting a function that when called returns the Go minor version) but I'd like to avoid such hacks if possible. Therefore I would propose keeping it as-is for now and only adding a workaround if there is enough demand (which I don't expect).
This will probably conflict with #1014 but the conflicts should be easy to resolve.

Go 1.14 support

---

transform/func-lowering.go
transform/testdata/func-lowering.ll
transform/testdata/func-lowering.out.ll

Previously, the function value lowering pass had special cases for when there were 0 or 1 function implementations. However, the results of the pass were incorrect in both of these cases. This change removes the specializations and fixes the transformation.
In the case that there was a single function implementation, the compiler emitted a select instruction to obtain the function pointer. This selected between null and the implementing function pointer.
While this was technically correct, it failed to eliminate indirect function calls. This prevented discovery of these calls by the coroutine lowering pass, and caused async function calls to be passed through unlowered. As a result, the generated code had undefined behavior (usually resulting in a segfault).
In the case of no function …

transform (func-lowering): remove specializations from function value lowering and fix lowering of a function value of an unimplemented type

---

src/runtime/chan.go
testdata/channel.go

Previously, a blocking select on a nil channel would result in a nil panic inside the channel runtime code. This change fixes the nil checks so that the select works as intended.
Fixes: #1047

runtime (chan): fix blocking select on a nil channel

---

targets/wasm_exec.js

These are only new things on the wasm side, so they should do nothing until the Go side starts calling them, which should only be in Go 1.14.

wasm_exec: Port over safe features

---

compiler/calls.go
compiler/compiler.go
compiler/sizes.go

Some symbols (constants/types/methods) were exported while they are an implementation detail. To keep the public API clean, unexport them.
The public API of the compiler package now consists of just the `Compile` and the `NewTargetMachine` functions.

compiler: unexport some exported symbols

---

main.go

This PR adds up to 3 retries when attempting to reset the target board by switching the serial port to 1200 baud speed change. Should hopefully help with boards that need a longer time to prepare their bootloader.

flash: retry 3 times when attempting to reset the serial port

---

src/runtime/scheduler_avr.S
src/runtime/scheduler_cortexm.S

This allows dead code elimination and avoids linker errors with `-scheduler=leaking`.

runtime: do not put scheduler and GC code in the same section

---

compiler/calls.go
compiler/compiler.go
compiler/func.go
compiler/interface.go

This makes viewing the IR easier because parameters have readable names.
This also makes it easier to write compiler tests (still a work in progress), that work in LLVM 9 and LLVM 10, as LLVM 10 started printing value names for unnamed parameters. Naming them would avoid that issue.
Example function:
```go
func printstring(s string)
```
Before:
```llvm
define internal void @runtime.printstring(i8* %0, i64 %1, i8* %context, i8* %parentHandle) unnamed_addr {
```
After:
```llvm
define internal void @runtime.printstring(i8* %s.data, i64 %s.len, i8* %context, i8* %parentHandle) unnamed_addr {
```

compiler: add parameter names to IR

---

src/runtime/scheduler_gba.S
targets/gameboy-advance.json

This is a continuation of #1058 that attempts to fix the issue on GBA. It now appears to link, but the display example does not appear to run right now:

runtime: copy stack scan assembly for GBA 

---

targets/gameboy-advance.json

This results in bigger code size, but it works around a bug in the linker.
The issue starts with the problem that libraries (picolibc, compiler-rt) were compiled as ARM and the rest as Thumb. This causes some blx instructions to be inserted by the linker to call into these libraries.
Ideally we should fix the libraries to use Thumb mode instead, but that requires some more extensive changes (including fixes to compiler-rt) and it's just way easier to use ARM mode everywhere.
fixes #894

gba: always use ARM mode instead of Thumb mode

---

src/runtime/scheduler_tinygoriscv.S

This fixes an infinite loop in the riscv scheduler caused by the `ra` register which gets overwritten.
The bug occures when `runtime.GC()` is called.

riscv: fix infinite loop in garbage collector

---

src/runtime/print.go

This function is called from `runtime.printitf`, which is called from `runtime._panic`, and is therefore the leaf function of many call paths. This makes analyzing stack usage very difficult.
Also forwarding `printuint32` to `printuint64` as it reduces code size in the few examples I've tested. Printing numbers is not often done so it doesn't matter if it's a bit slow (the serial connection is probably slower anyway).

runtime: avoid recursion in printuint64 function

---

builder/picolibc.go
compileopts/config.go

Previously we used `--sysroot` to set the sysroot explicitly. Unfortunately, this flag is not used directly by Clang to set the include path (`<sysroot>/include`) but is instead interpreted by the toolchain code. This means that even when the toolchain is explicitly set (using the `--sysroot` parameter), it may still decide to use a different include path such as `<sysroot>/usr/include` (such as on baremetal aarch64).
This commit uses the Clang-internal `-internal-isystem` flag which sets the include directory directly (as a system include path). This should be more robust.
The reason the `--sysroot` parameter has so far worked is that all existing targets happened to add `<sysroot>/include` as an include path.
The relevant Clang code is here: …

builder: fix picolibc include path

---

go.mod
go.sum

The go-llvm package was still trying to use LLVM version 9 on MacOS.

main: update go-llvm to fix macOS build problem

---

transform/func-lowering.go

This commit fixes errors like the following:
inlinable function call in a function with debug info must have a !dbg location
call void @runtime.nilPanic(i8* undef, i8* null)
inlinable function call in a function with debug info must have a !dbg location
%24 = call fastcc %runtime._interface @"(*github.com/vugu/vugu/domrender.JSRenderer).render$1"(%"github.com/vugu/vugu.VGNode"** %19, i32 %22, i32 %23, i8* %15, i8* undef)
error: optimizations caused a verification failure
Not all instructions had a debug location, which apparently caused issues for the inliner.
This was a problem when trying to compile Vugu.

transform: fix debug information in func lowering pass

---

targets/atsamd51j20a.json
targets/atsamd51j20a.ld

In this PR, I'll correct the linker script.
ROM size of the atsamd51j20a is 1024KB, not 512KB.
RAM size is 256KB, not 192KB.

Fix ROM / RAM size on atsamd51j20

---

src/internal/task/queue.go
src/sync/cond.go
src/sync/mutex.go
src/sync/waitgroup.go
testdata/channel.go
testdata/coroutines.go
testdata/coroutines.txt

This is based on top of #828 and adds full support for the `sync` package, implementing blocking by using the `internal/task` package.

Implement `sync`

---

targets/arduino-nano33.json

This PR uses the `-U` flag to ensure that device can be found by `bossac` flashing tool when the Arduino Nano33 IoT is not connected to the default port.

machine/arduino-nano33: use USB flag and remove debug flag for bossac flasher

---

src/runtime/gc_extalloc.go

When using `-gc extalloc` and an import of `golang.org/x/sys/unix` the compile failed due to:
```
../../vendor/golang.org/x/sys/unix/ioctl.go:30:10: KeepAlive not declared by package runtime
../../vendor/golang.org/x/sys/unix/ioctl.go:40:10: KeepAlive not declared by package runtime
../../vendor/golang.org/x/sys/unix/syscall_linux.go:96:10: KeepAlive not declared by package runtime
```

runtime: fix compilation errors when using gc.extalloc

---

src/os/proc.go
src/runtime/runtime.go

Tnis allows code that relies on it to compile, the `flags` package compiles now. No real parameters are passed but Args[0] contains a static mock string.
Setting Args as recommended https://github.com/tinygo-org/tinygo/issues/541#issuecomment-531483733 did not work tho:
`tinygo/src/runtime/runtime_unix.go`
```
func main() int {
args = []string{"/proc/self/exe2"}
preinit()
run()
```
has no effect, os.Args will still hold the old value

os: add Args stub

---

src/os/file.go
src/os/file_other.go
src/os/file_unix.go
src/os/filesystem.go
src/syscall/syscall_darwin.go
src/syscall/syscall_libc.go
testdata/stdlib.go
testdata/stdlib.txt

This allows applications to mount filesystems in the os package. This is useful for mounting external flash filesystems, for example.
TODO: this is not finished: there is no support yet for paths relative to the current working directory.
Question: do we even want such a thing? Or is the Go `io.Writer` / `io.Reader` etc abstraction enough?

os: implement virtual filesystem support

---

.circleci/config.yml

We don't need it anymore since we use lld to link RISC-V binaries.

ci: do not install the SiFive toolchain

---

.circleci/config.yml
Makefile
azure-pipelines.yml

This should make installing TinyGo easier on Debian based systems by automatically creating a symlink in `/usr/local/bin`. For example, see #1103 and #725. It also makes the release process a little bit more robust and reproducible as the Debian package is built in CI instead of on my laptop.
fixes #725

ci: build .deb files along with .tar.gz files for Debian

---

src/examples/pwm/pwm.go
src/machine/machine_atmega328p.go
src/machine/machine_atsamd21.go
src/machine/machine_atsamd51.go
src/machine/machine_generic.go
src/machine/machine_nrf52.go
src/machine/machine_nrf52840.go

Previously it would trigger a nil pointer panic.
fixes #1038

sam: return an error when an incorrect PWM pin is used

---

compileopts/config.go
compileopts/options.go
compileopts/options_test.go
main.go

PR for https://github.com/tinygo-org/tinygo/issues/1062

compileopts: improve error reporting of unsupported flags

---

src/runtime/runtime_wasm.go

Adding scheduler call per discussion with @jaddr2line here https://github.com/tinygo-org/tinygo/issues/1091 resolves the issue where JS event handlers are not executing anything.  I tested this on two examples which were exhibiting the bug and both are working now.

call scheduler from resume

---

src/examples/button/button.go
src/machine/machine_atmega1284p.go
src/machine/machine_atmega2560.go
src/machine/machine_atmega328p.go
src/machine/machine_attiny85.go
src/machine/machine_avr.go

This PR contains two somewhat related (but distinct) commits:
1. A refactor of AVR GPIO pins. It reduces duplication and at with that, also reduces the amount of new code needed when adding support for a new AVR chip. Additionally, I discovered a bug in the ATmega2560 `Pin.Get()` function which is fixed in the unified `Pin.Get()` function.
2. Added support for `PinInputPullup`. The motivation for the refactor was to make this simpler to implement, and as a result this only needed a code change in one place.
`PinInputPullup` will make AVR pin interrupt support much easier to use. I have code for that that I just need to clean up, but I thought it would be a good idea to make this PR separately first.
I have tested this on an Arduino Uno and a DigiSpark. Note that for the DigiSpark, you …

AVR PinInputPullup

---

builder/library.go
targets/atsamd51g19a.json
targets/atsamd51j19a.json
targets/atsamd51j20a.json
targets/cortex-m4.json
targets/nrf52.json
targets/nrf52840.json
targets/stm32f4disco.json

Eventually we might want to start using the FPU, but the easy option right now is to simply disable it everywhere. Previously, it depended on whether Clang was built as part of TinyGo or it was an external binary (but Go code compiled with TinyGo never used the FPU). By setting the floating point mode explicitly, such inconsistencies are avoided.
This commit creates a new cortex-m4 target which can be the central place for setting FPU-related settings across all Cortex-M4 chips.
Tested on the pca10040 and the ItsyBitsy-m4.

arm: make FPU configuration consistent

---

Makefile
builder/config.go
builder/env.go
compiler/compiler.go
goenv/version.go
ir/ir.go
loader/errors.go
loader/goroot.go
loader/loader.go
main.go
main_test.go
version.go

This is more of a mockup than anything serious. I want to see whether creating a new GOROOT per build is feasible. Right now creating such a GOROOT costs about 4ms on my system (after a warmed-up cache) so is not a significant overhead per build.
I'm not sure whether the current approach (with symlinks) is going to be viable on Windows.
The first commit adds the `go list` command, which might be enough to support TinyGo in IDEs such as VS Code.

Go module support

---

Makefile
src/examples/pininterrupt/circuitplay-express.go
src/examples/pininterrupt/pca10040.go
src/examples/pininterrupt/pininterrupt.go
src/machine/machine.go
src/machine/machine_atsamd21.go
src/machine/machine_nrf.go

This PR implements pin interrupts for Nordic devices and for SAM D21 devices.
I have kept the API very simple, so it is easy to generalize to many different microcontrollers. It is also possible to make it faster, but that would make the API also less flexible. Right now it will just read the callback from a global, which should be good enough for most purposes.
Something else that it doesn't implement (yet) is level interrupts (as opposed to edge interrupts). Level interrupts, while (probably) easier to implement in hardware, are harder to use in practice. The main advantage of level interrupts appears to be that some chips support them even in very low power states. For simplicity, I've just left them out in this version.
I have also implemented interrupts for AVR devices (Arduino Uno …

Implement pin interrupts

---

main.go

#1077 
This PR solves a problem that causes tinygo flash to fail in a windows environment.
The fix isn't the right one, but it's a step forward because until now it wasn't possible to `tinygo flash` the `flash-method == msd target` on windows.
I use runtime.GOOS to affect only windows.
Also, even if you get the judgement wrong, it should fail on subsequent msd-volume-name checks.
BEFORE: We couldn't tinygo flash in windows + msd
AFTER: We can do tinygo flash with windows + msd too!
I'd like to see it merged, as it would be more convenient for windows users (who don't have jlink, etc.).

flash: fix touchSerialPortAt1200bps on windows

---

.circleci/config.yml

Adds the arch-release job, which automatically updates
the tinygo-bin AUR package on every new git tag with
a semver version.
This will require setting the `$ARCH_RELEASE_SSH_PRIVATE_KEY` secret CI variable to a value that I have transferred to @deadprogram.

ci: add archlinux release job

---

Makefile
builder/build.go
builder/esp.go
src/device/esp/esp8266.S
src/machine/board_nodemcu.go
src/machine/machine_esp8266.go
src/runtime/runtime_esp8266.go
targets/esp8266.json
targets/esp8266.ld
targets/nodemcu.json

To use this, use LLVM with Xtensa support:
https://github.com/espressif/llvm-project
Make sure you modify the CMake command (in the Makefile) to include the Xtensa backend:
-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR;Xtensa
You will also need to install the esp8266 GCC toolchain for the `xtensa-lx106-elf-ld` linker (lld doesn't yet support Xtensa).
I have used a NodeMCU dev board (clone?) to test this PR. Unfortunately, you can't yet flash it directly using `tinygo flash`, instead you have to use some `esptool.py` commands:
tinygo build -o image.elf -target=nodemcu examples/blinky1
esptool.py elf2image image.elf
esptool.py --port /dev/ttyUSB0 write_flash 0x00000 image.elf-0x00000.bin -ff 80m -fm dout
Many thanks to @CNLohr for the [nosdk8266 project](https://github.com/cnlohr/nosdk8266). …

Add support for the ESP8266

---

.circleci/config.yml
builder/build.go
builder/objcopy.go
cgo/libclang_config.go
cgo/libclang_config_llvm11.go
go.mod
go.sum
interp/interp_test.go
targets/gameboy-advance.ld
transform/globals.go
transform/transform_test.go

This can be useful to test improvements in LLVM master and to make it
possible to support LLVM 11 for the most part already before the next
release. That also allows catching LLVM bugs early to fix them upstream.
Note that tests do not yet pass for this LLVM version, but the TinyGo
compiler can be built with the binaries from apt.llvm.org (at the time
of making this commit).
---
One concrete example of what I want to do with this change is to test/improve AVR support: upstream master has a number of improvements that aren't included yet in LLVM 10.
Note that #1055 should be merged first.

main: add support for LLVM 11

---

main.go
targets/avr.json

Be able to run `tinygo gdb -target=arduino ./testdata/alias.go` and debug a program with the power of a real debugger.
Note that this only works on LLVM 11 (see #1056) because older versions have a bug in the AVR backend that cause it to produce invalid debug information: https://reviews.llvm.org/D74213.

main: support gdb debugging with AVR
